// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emaildomainmapping.sql

package dbq

import (
	"context"
	"time"
)

const emailDomainMapping2FAMethodInsert = `-- name: EmailDomainMapping2FAMethodInsert :exec
INSERT INTO tnt_email_domain_mapping_2fa_methods
    (email_domain_mapping_id, method)
VALUES ($1, $2)
`

type EmailDomainMapping2FAMethodInsertParams struct {
	EmailDomainMappingID string
	Method               string
}

func (q *Queries) EmailDomainMapping2FAMethodInsert(ctx context.Context, arg EmailDomainMapping2FAMethodInsertParams) error {
	_, err := q.db.Exec(ctx, emailDomainMapping2FAMethodInsert, arg.EmailDomainMappingID, arg.Method)
	return err
}

const emailDomainMapping2FAMethodsClear = `-- name: EmailDomainMapping2FAMethodsClear :exec
DELETE FROM tnt_email_domain_mapping_2fa_methods
WHERE email_domain_mapping_id = $1
`

func (q *Queries) EmailDomainMapping2FAMethodsClear(ctx context.Context, emailDomainMappingID string) error {
	_, err := q.db.Exec(ctx, emailDomainMapping2FAMethodsClear, emailDomainMappingID)
	return err
}

const emailDomainMapping2FAMethodsForMappings = `-- name: EmailDomainMapping2FAMethodsForMappings :many
SELECT email_domain_mapping_id, method
FROM tnt_email_domain_mapping_2fa_methods
WHERE email_domain_mapping_id = ANY($1::varchar[])
`

type EmailDomainMapping2FAMethodsForMappingsRow struct {
	EmailDomainMappingID string
	Method               string
}

func (q *Queries) EmailDomainMapping2FAMethodsForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMapping2FAMethodsForMappingsRow, error) {
	rows, err := q.db.Query(ctx, emailDomainMapping2FAMethodsForMappings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailDomainMapping2FAMethodsForMappingsRow{}
	for rows.Next() {
		var i EmailDomainMapping2FAMethodsForMappingsRow
		if err := rows.Scan(&i.EmailDomainMappingID, &i.Method); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const emailDomainMappingAdditionalClientInsert = `-- name: EmailDomainMappingAdditionalClientInsert :exec
INSERT INTO tnt_email_domain_mapping_additional_clients
    (email_domain_mapping_id, client_id)
VALUES ($1, $2)
`

type EmailDomainMappingAdditionalClientInsertParams struct {
	EmailDomainMappingID string
	ClientID             string
}

func (q *Queries) EmailDomainMappingAdditionalClientInsert(ctx context.Context, arg EmailDomainMappingAdditionalClientInsertParams) error {
	_, err := q.db.Exec(ctx, emailDomainMappingAdditionalClientInsert, arg.EmailDomainMappingID, arg.ClientID)
	return err
}

const emailDomainMappingAdditionalClientsClear = `-- name: EmailDomainMappingAdditionalClientsClear :exec

DELETE FROM tnt_email_domain_mapping_additional_clients
WHERE email_domain_mapping_id = $1
`

// ── junctions: clear + insert ─────────────────────────────────────────
func (q *Queries) EmailDomainMappingAdditionalClientsClear(ctx context.Context, emailDomainMappingID string) error {
	_, err := q.db.Exec(ctx, emailDomainMappingAdditionalClientsClear, emailDomainMappingID)
	return err
}

const emailDomainMappingAdditionalClientsForMappings = `-- name: EmailDomainMappingAdditionalClientsForMappings :many

SELECT email_domain_mapping_id, client_id
FROM tnt_email_domain_mapping_additional_clients
WHERE email_domain_mapping_id = ANY($1::varchar[])
`

type EmailDomainMappingAdditionalClientsForMappingsRow struct {
	EmailDomainMappingID string
	ClientID             string
}

// ── junctions: batch hydrate via ANY($1) ─────────────────────────────
func (q *Queries) EmailDomainMappingAdditionalClientsForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMappingAdditionalClientsForMappingsRow, error) {
	rows, err := q.db.Query(ctx, emailDomainMappingAdditionalClientsForMappings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailDomainMappingAdditionalClientsForMappingsRow{}
	for rows.Next() {
		var i EmailDomainMappingAdditionalClientsForMappingsRow
		if err := rows.Scan(&i.EmailDomainMappingID, &i.ClientID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const emailDomainMappingAllowedRoleInsert = `-- name: EmailDomainMappingAllowedRoleInsert :exec
INSERT INTO tnt_email_domain_mapping_allowed_roles
    (email_domain_mapping_id, role_id)
VALUES ($1, $2)
`

type EmailDomainMappingAllowedRoleInsertParams struct {
	EmailDomainMappingID string
	RoleID               string
}

func (q *Queries) EmailDomainMappingAllowedRoleInsert(ctx context.Context, arg EmailDomainMappingAllowedRoleInsertParams) error {
	_, err := q.db.Exec(ctx, emailDomainMappingAllowedRoleInsert, arg.EmailDomainMappingID, arg.RoleID)
	return err
}

const emailDomainMappingAllowedRolesClear = `-- name: EmailDomainMappingAllowedRolesClear :exec
DELETE FROM tnt_email_domain_mapping_allowed_roles
WHERE email_domain_mapping_id = $1
`

func (q *Queries) EmailDomainMappingAllowedRolesClear(ctx context.Context, emailDomainMappingID string) error {
	_, err := q.db.Exec(ctx, emailDomainMappingAllowedRolesClear, emailDomainMappingID)
	return err
}

const emailDomainMappingAllowedRolesForMappings = `-- name: EmailDomainMappingAllowedRolesForMappings :many
SELECT email_domain_mapping_id, role_id
FROM tnt_email_domain_mapping_allowed_roles
WHERE email_domain_mapping_id = ANY($1::varchar[])
`

type EmailDomainMappingAllowedRolesForMappingsRow struct {
	EmailDomainMappingID string
	RoleID               string
}

func (q *Queries) EmailDomainMappingAllowedRolesForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMappingAllowedRolesForMappingsRow, error) {
	rows, err := q.db.Query(ctx, emailDomainMappingAllowedRolesForMappings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailDomainMappingAllowedRolesForMappingsRow{}
	for rows.Next() {
		var i EmailDomainMappingAllowedRolesForMappingsRow
		if err := rows.Scan(&i.EmailDomainMappingID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const emailDomainMappingDelete = `-- name: EmailDomainMappingDelete :exec
DELETE FROM tnt_email_domain_mappings WHERE id = $1
`

func (q *Queries) EmailDomainMappingDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, emailDomainMappingDelete, id)
	return err
}

const emailDomainMappingFindAll = `-- name: EmailDomainMappingFindAll :many
SELECT id, email_domain, identity_provider_id, scope_type, primary_client_id,
       required_oidc_tenant_id, sync_roles_from_idp, created_at, updated_at,
       require_2fa, remember_device_enabled, remember_device_days
FROM tnt_email_domain_mappings
ORDER BY email_domain
`

func (q *Queries) EmailDomainMappingFindAll(ctx context.Context) ([]TntEmailDomainMapping, error) {
	rows, err := q.db.Query(ctx, emailDomainMappingFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TntEmailDomainMapping{}
	for rows.Next() {
		var i TntEmailDomainMapping
		if err := rows.Scan(
			&i.ID,
			&i.EmailDomain,
			&i.IdentityProviderID,
			&i.ScopeType,
			&i.PrimaryClientID,
			&i.RequiredOidcTenantID,
			&i.SyncRolesFromIdp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Require2fa,
			&i.RememberDeviceEnabled,
			&i.RememberDeviceDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const emailDomainMappingFindByDomain = `-- name: EmailDomainMappingFindByDomain :one
SELECT id, email_domain, identity_provider_id, scope_type, primary_client_id,
       required_oidc_tenant_id, sync_roles_from_idp, created_at, updated_at,
       require_2fa, remember_device_enabled, remember_device_days
FROM tnt_email_domain_mappings
WHERE email_domain = $1
`

func (q *Queries) EmailDomainMappingFindByDomain(ctx context.Context, emailDomain string) (TntEmailDomainMapping, error) {
	row := q.db.QueryRow(ctx, emailDomainMappingFindByDomain, emailDomain)
	var i TntEmailDomainMapping
	err := row.Scan(
		&i.ID,
		&i.EmailDomain,
		&i.IdentityProviderID,
		&i.ScopeType,
		&i.PrimaryClientID,
		&i.RequiredOidcTenantID,
		&i.SyncRolesFromIdp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Require2fa,
		&i.RememberDeviceEnabled,
		&i.RememberDeviceDays,
	)
	return i, err
}

const emailDomainMappingFindByID = `-- name: EmailDomainMappingFindByID :one

SELECT id, email_domain, identity_provider_id, scope_type, primary_client_id,
       required_oidc_tenant_id, sync_roles_from_idp, created_at, updated_at,
       require_2fa, remember_device_enabled, remember_device_days
FROM tnt_email_domain_mappings
WHERE id = $1
`

// Queries for tnt_email_domain_mappings + its junction tables
// (additional_clients, granted_clients, allowed_roles, 2fa_methods).
// None of the junctions declare FK ON DELETE CASCADE, so Delete must
// clean them explicitly. Mirrors the Rust impl (2fa_methods is Go-only).
func (q *Queries) EmailDomainMappingFindByID(ctx context.Context, id string) (TntEmailDomainMapping, error) {
	row := q.db.QueryRow(ctx, emailDomainMappingFindByID, id)
	var i TntEmailDomainMapping
	err := row.Scan(
		&i.ID,
		&i.EmailDomain,
		&i.IdentityProviderID,
		&i.ScopeType,
		&i.PrimaryClientID,
		&i.RequiredOidcTenantID,
		&i.SyncRolesFromIdp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Require2fa,
		&i.RememberDeviceEnabled,
		&i.RememberDeviceDays,
	)
	return i, err
}

const emailDomainMappingGrantedClientInsert = `-- name: EmailDomainMappingGrantedClientInsert :exec
INSERT INTO tnt_email_domain_mapping_granted_clients
    (email_domain_mapping_id, client_id)
VALUES ($1, $2)
`

type EmailDomainMappingGrantedClientInsertParams struct {
	EmailDomainMappingID string
	ClientID             string
}

func (q *Queries) EmailDomainMappingGrantedClientInsert(ctx context.Context, arg EmailDomainMappingGrantedClientInsertParams) error {
	_, err := q.db.Exec(ctx, emailDomainMappingGrantedClientInsert, arg.EmailDomainMappingID, arg.ClientID)
	return err
}

const emailDomainMappingGrantedClientsClear = `-- name: EmailDomainMappingGrantedClientsClear :exec
DELETE FROM tnt_email_domain_mapping_granted_clients
WHERE email_domain_mapping_id = $1
`

func (q *Queries) EmailDomainMappingGrantedClientsClear(ctx context.Context, emailDomainMappingID string) error {
	_, err := q.db.Exec(ctx, emailDomainMappingGrantedClientsClear, emailDomainMappingID)
	return err
}

const emailDomainMappingGrantedClientsForMappings = `-- name: EmailDomainMappingGrantedClientsForMappings :many
SELECT email_domain_mapping_id, client_id
FROM tnt_email_domain_mapping_granted_clients
WHERE email_domain_mapping_id = ANY($1::varchar[])
`

type EmailDomainMappingGrantedClientsForMappingsRow struct {
	EmailDomainMappingID string
	ClientID             string
}

func (q *Queries) EmailDomainMappingGrantedClientsForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMappingGrantedClientsForMappingsRow, error) {
	rows, err := q.db.Query(ctx, emailDomainMappingGrantedClientsForMappings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailDomainMappingGrantedClientsForMappingsRow{}
	for rows.Next() {
		var i EmailDomainMappingGrantedClientsForMappingsRow
		if err := rows.Scan(&i.EmailDomainMappingID, &i.ClientID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const emailDomainMappingUpsert = `-- name: EmailDomainMappingUpsert :exec
INSERT INTO tnt_email_domain_mappings
    (id, email_domain, identity_provider_id, scope_type, primary_client_id,
     required_oidc_tenant_id, sync_roles_from_idp, require_2fa,
     remember_device_enabled, remember_device_days, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    email_domain = EXCLUDED.email_domain,
    identity_provider_id = EXCLUDED.identity_provider_id,
    scope_type = EXCLUDED.scope_type,
    primary_client_id = EXCLUDED.primary_client_id,
    required_oidc_tenant_id = EXCLUDED.required_oidc_tenant_id,
    sync_roles_from_idp = EXCLUDED.sync_roles_from_idp,
    require_2fa = EXCLUDED.require_2fa,
    remember_device_enabled = EXCLUDED.remember_device_enabled,
    remember_device_days = EXCLUDED.remember_device_days,
    updated_at = EXCLUDED.updated_at
`

type EmailDomainMappingUpsertParams struct {
	ID                    string
	EmailDomain           string
	IdentityProviderID    string
	ScopeType             string
	PrimaryClientID       *string
	RequiredOidcTenantID  *string
	SyncRolesFromIdp      bool
	Require2fa            bool
	RememberDeviceEnabled bool
	RememberDeviceDays    int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) EmailDomainMappingUpsert(ctx context.Context, arg EmailDomainMappingUpsertParams) error {
	_, err := q.db.Exec(ctx, emailDomainMappingUpsert,
		arg.ID,
		arg.EmailDomain,
		arg.IdentityProviderID,
		arg.ScopeType,
		arg.PrimaryClientID,
		arg.RequiredOidcTenantID,
		arg.SyncRolesFromIdp,
		arg.Require2fa,
		arg.RememberDeviceEnabled,
		arg.RememberDeviceDays,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
