// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eventtype.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const eventTypeDelete = `-- name: EventTypeDelete :exec
DELETE FROM msg_event_types WHERE id = $1
`

func (q *Queries) EventTypeDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, eventTypeDelete, id)
	return err
}

const eventTypeFindByApplication = `-- name: EventTypeFindByApplication :many
SELECT id, code, name, description, status, source, client_scoped,
       application, subdomain, aggregate, created_at, updated_at, created_by
FROM msg_event_types
WHERE application = $1
ORDER BY code
`

func (q *Queries) EventTypeFindByApplication(ctx context.Context, application string) ([]MsgEventType, error) {
	rows, err := q.db.Query(ctx, eventTypeFindByApplication, application)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgEventType{}
	for rows.Next() {
		var i MsgEventType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Source,
			&i.ClientScoped,
			&i.Application,
			&i.Subdomain,
			&i.Aggregate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventTypeFindByCode = `-- name: EventTypeFindByCode :one
SELECT id, code, name, description, status, source, client_scoped,
       application, subdomain, aggregate, created_at, updated_at, created_by
FROM msg_event_types
WHERE code = $1
`

func (q *Queries) EventTypeFindByCode(ctx context.Context, code string) (MsgEventType, error) {
	row := q.db.QueryRow(ctx, eventTypeFindByCode, code)
	var i MsgEventType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Source,
		&i.ClientScoped,
		&i.Application,
		&i.Subdomain,
		&i.Aggregate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const eventTypeFindByID = `-- name: EventTypeFindByID :one

SELECT id, code, name, description, status, source, client_scoped,
       application, subdomain, aggregate, created_at, updated_at, created_by
FROM msg_event_types
WHERE id = $1
`

// Queries for msg_event_types + msg_event_type_spec_versions.
// Two upsert variants: ON CONFLICT (id) for the canonical path, and
// ON CONFLICT (code) for the sync use case which keys by code.
func (q *Queries) EventTypeFindByID(ctx context.Context, id string) (MsgEventType, error) {
	row := q.db.QueryRow(ctx, eventTypeFindByID, id)
	var i MsgEventType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Source,
		&i.ClientScoped,
		&i.Application,
		&i.Subdomain,
		&i.Aggregate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const eventTypeUpsertByCode = `-- name: EventTypeUpsertByCode :exec
INSERT INTO msg_event_types
    (id, code, name, description, status, source, client_scoped,
     application, subdomain, aggregate, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    source = EXCLUDED.source,
    client_scoped = EXCLUDED.client_scoped,
    updated_at = EXCLUDED.updated_at
`

type EventTypeUpsertByCodeParams struct {
	ID           string    `db:"id"`
	Code         string    `db:"code"`
	Name         string    `db:"name"`
	Description  *string   `db:"description"`
	Status       string    `db:"status"`
	Source       string    `db:"source"`
	ClientScoped bool      `db:"client_scoped"`
	Application  string    `db:"application"`
	Subdomain    string    `db:"subdomain"`
	Aggregate    string    `db:"aggregate"`
	CreatedBy    *string   `db:"created_by"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) EventTypeUpsertByCode(ctx context.Context, arg EventTypeUpsertByCodeParams) error {
	_, err := q.db.Exec(ctx, eventTypeUpsertByCode,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Source,
		arg.ClientScoped,
		arg.Application,
		arg.Subdomain,
		arg.Aggregate,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const eventTypeUpsertByID = `-- name: EventTypeUpsertByID :exec
INSERT INTO msg_event_types
    (id, code, name, description, status, source, client_scoped,
     application, subdomain, aggregate, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    source = EXCLUDED.source,
    client_scoped = EXCLUDED.client_scoped,
    application = EXCLUDED.application,
    subdomain = EXCLUDED.subdomain,
    aggregate = EXCLUDED.aggregate,
    updated_at = EXCLUDED.updated_at
`

type EventTypeUpsertByIDParams struct {
	ID           string    `db:"id"`
	Code         string    `db:"code"`
	Name         string    `db:"name"`
	Description  *string   `db:"description"`
	Status       string    `db:"status"`
	Source       string    `db:"source"`
	ClientScoped bool      `db:"client_scoped"`
	Application  string    `db:"application"`
	Subdomain    string    `db:"subdomain"`
	Aggregate    string    `db:"aggregate"`
	CreatedBy    *string   `db:"created_by"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

func (q *Queries) EventTypeUpsertByID(ctx context.Context, arg EventTypeUpsertByIDParams) error {
	_, err := q.db.Exec(ctx, eventTypeUpsertByID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Source,
		arg.ClientScoped,
		arg.Application,
		arg.Subdomain,
		arg.Aggregate,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const specVersionUpsert = `-- name: SpecVersionUpsert :exec
INSERT INTO msg_event_type_spec_versions
    (id, event_type_id, version, mime_type, schema_content, schema_type,
     status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    schema_content = EXCLUDED.schema_content,
    schema_type = EXCLUDED.schema_type,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
`

type SpecVersionUpsertParams struct {
	ID            string          `db:"id"`
	EventTypeID   string          `db:"event_type_id"`
	Version       string          `db:"version"`
	MimeType      string          `db:"mime_type"`
	SchemaContent json.RawMessage `db:"schema_content"`
	SchemaType    string          `db:"schema_type"`
	Status        string          `db:"status"`
	CreatedAt     time.Time       `db:"created_at"`
	UpdatedAt     time.Time       `db:"updated_at"`
}

func (q *Queries) SpecVersionUpsert(ctx context.Context, arg SpecVersionUpsertParams) error {
	_, err := q.db.Exec(ctx, specVersionUpsert,
		arg.ID,
		arg.EventTypeID,
		arg.Version,
		arg.MimeType,
		arg.SchemaContent,
		arg.SchemaType,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const specVersionsClear = `-- name: SpecVersionsClear :exec
DELETE FROM msg_event_type_spec_versions WHERE event_type_id = $1
`

func (q *Queries) SpecVersionsClear(ctx context.Context, eventTypeID string) error {
	_, err := q.db.Exec(ctx, specVersionsClear, eventTypeID)
	return err
}

const specVersionsForEventTypes = `-- name: SpecVersionsForEventTypes :many
SELECT id, event_type_id, version, mime_type, schema_content, schema_type,
       status, created_at, updated_at
FROM msg_event_type_spec_versions
WHERE event_type_id = ANY($1::text[])
ORDER BY event_type_id, version
`

func (q *Queries) SpecVersionsForEventTypes(ctx context.Context, eventTypeIds []string) ([]MsgEventTypeSpecVersion, error) {
	rows, err := q.db.Query(ctx, specVersionsForEventTypes, eventTypeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgEventTypeSpecVersion{}
	for rows.Next() {
		var i MsgEventTypeSpecVersion
		if err := rows.Scan(
			&i.ID,
			&i.EventTypeID,
			&i.Version,
			&i.MimeType,
			&i.SchemaContent,
			&i.SchemaType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
