// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"encoding/json"
	"time"
)

type AppApplication struct {
	ID               string    `db:"id"`
	Type             string    `db:"type"`
	Code             string    `db:"code"`
	Name             string    `db:"name"`
	Description      *string   `db:"description"`
	IconUrl          *string   `db:"icon_url"`
	Website          *string   `db:"website"`
	Logo             *string   `db:"logo"`
	LogoMimeType     *string   `db:"logo_mime_type"`
	DefaultBaseUrl   *string   `db:"default_base_url"`
	ServiceAccountID *string   `db:"service_account_id"`
	Active           bool      `db:"active"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
}

type AppApplicationOpenapiSpec struct {
	ID              string          `db:"id"`
	ApplicationID   string          `db:"application_id"`
	Version         string          `db:"version"`
	Status          string          `db:"status"`
	Spec            json.RawMessage `db:"spec"`
	SpecHash        string          `db:"spec_hash"`
	ChangeNotes     json.RawMessage `db:"change_notes"`
	ChangeNotesText *string         `db:"change_notes_text"`
	SyncedAt        time.Time       `db:"synced_at"`
	SyncedBy        *string         `db:"synced_by"`
	CreatedAt       time.Time       `db:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at"`
}

type AppClientConfig struct {
	ID            string    `db:"id"`
	ApplicationID string    `db:"application_id"`
	ClientID      string    `db:"client_id"`
	Enabled       bool      `db:"enabled"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

type AppPlatformConfig struct {
	ID              string    `db:"id"`
	ApplicationCode string    `db:"application_code"`
	Section         string    `db:"section"`
	Property        string    `db:"property"`
	Scope           string    `db:"scope"`
	ClientID        *string   `db:"client_id"`
	ValueType       string    `db:"value_type"`
	Value           string    `db:"value"`
	Description     *string   `db:"description"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
}

type AppPlatformConfigAccess struct {
	ID              string    `db:"id"`
	ApplicationCode string    `db:"application_code"`
	RoleCode        string    `db:"role_code"`
	CanRead         bool      `db:"can_read"`
	CanWrite        bool      `db:"can_write"`
	CreatedAt       time.Time `db:"created_at"`
}

type AudLog struct {
	ID            string          `db:"id"`
	EntityType    string          `db:"entity_type"`
	EntityID      string          `db:"entity_id"`
	Operation     string          `db:"operation"`
	OperationJson json.RawMessage `db:"operation_json"`
	PrincipalID   *string         `db:"principal_id"`
	PerformedAt   time.Time       `db:"performed_at"`
	ApplicationID *string         `db:"application_id"`
	ClientID      *string         `db:"client_id"`
}

type IamAuthorizationCode struct {
	Code                string    `db:"code"`
	ClientID            string    `db:"client_id"`
	PrincipalID         string    `db:"principal_id"`
	RedirectUri         string    `db:"redirect_uri"`
	Scope               *string   `db:"scope"`
	CodeChallenge       *string   `db:"code_challenge"`
	CodeChallengeMethod *string   `db:"code_challenge_method"`
	Nonce               *string   `db:"nonce"`
	State               *string   `db:"state"`
	ContextClientID     *string   `db:"context_client_id"`
	CreatedAt           time.Time `db:"created_at"`
	ExpiresAt           time.Time `db:"expires_at"`
	Used                bool      `db:"used"`
}

type IamClientAccessGrant struct {
	ID          string    `db:"id"`
	PrincipalID string    `db:"principal_id"`
	ClientID    string    `db:"client_id"`
	GrantedBy   string    `db:"granted_by"`
	GrantedAt   time.Time `db:"granted_at"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type IamLoginAttempt struct {
	ID            string    `db:"id"`
	AttemptType   string    `db:"attempt_type"`
	Outcome       string    `db:"outcome"`
	FailureReason *string   `db:"failure_reason"`
	Identifier    *string   `db:"identifier"`
	PrincipalID   *string   `db:"principal_id"`
	IpAddress     *string   `db:"ip_address"`
	UserAgent     *string   `db:"user_agent"`
	AttemptedAt   time.Time `db:"attempted_at"`
}

type IamMfaEmailPin struct {
	ID          string    `db:"id"`
	PrincipalID string    `db:"principal_id"`
	Purpose     string    `db:"purpose"`
	PinHash     string    `db:"pin_hash"`
	Attempts    int32     `db:"attempts"`
	ExpiresAt   time.Time `db:"expires_at"`
	CreatedAt   time.Time `db:"created_at"`
}

type IamMfaTrustedDevice struct {
	ID          string     `db:"id"`
	PrincipalID string     `db:"principal_id"`
	TokenHash   string     `db:"token_hash"`
	Label       *string    `db:"label"`
	ExpiresAt   time.Time  `db:"expires_at"`
	CreatedAt   time.Time  `db:"created_at"`
	LastUsedAt  *time.Time `db:"last_used_at"`
}

type IamOidcLoginState struct {
	State                    string    `db:"state"`
	EmailDomain              string    `db:"email_domain"`
	AuthConfigID             string    `db:"auth_config_id"`
	Nonce                    string    `db:"nonce"`
	CodeVerifier             string    `db:"code_verifier"`
	ReturnUrl                *string   `db:"return_url"`
	OauthClientID            *string   `db:"oauth_client_id"`
	OauthRedirectUri         *string   `db:"oauth_redirect_uri"`
	OauthScope               *string   `db:"oauth_scope"`
	OauthState               *string   `db:"oauth_state"`
	OauthCodeChallenge       *string   `db:"oauth_code_challenge"`
	OauthCodeChallengeMethod *string   `db:"oauth_code_challenge_method"`
	OauthNonce               *string   `db:"oauth_nonce"`
	CreatedAt                time.Time `db:"created_at"`
	ExpiresAt                time.Time `db:"expires_at"`
}

type IamPasswordResetToken struct {
	ID             string    `db:"id"`
	PrincipalID    string    `db:"principal_id"`
	TokenHash      string    `db:"token_hash"`
	ExpiresAt      time.Time `db:"expires_at"`
	CreatedAt      time.Time `db:"created_at"`
	Purpose        string    `db:"purpose"`
	Reset2fa       bool      `db:"reset_2fa"`
	RequiresFactor bool      `db:"requires_factor"`
	FactorAttempts int32     `db:"factor_attempts"`
}

type IamPermission struct {
	ID          string    `db:"id"`
	Code        string    `db:"code"`
	Subdomain   string    `db:"subdomain"`
	Context     string    `db:"context"`
	Aggregate   string    `db:"aggregate"`
	Action      string    `db:"action"`
	Description *string   `db:"description"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type IamPrincipal struct {
	ID               string     `db:"id"`
	Type             string     `db:"type"`
	Scope            *string    `db:"scope"`
	ClientID         *string    `db:"client_id"`
	ApplicationID    *string    `db:"application_id"`
	Name             string     `db:"name"`
	Active           bool       `db:"active"`
	Email            *string    `db:"email"`
	EmailDomain      *string    `db:"email_domain"`
	IdpType          *string    `db:"idp_type"`
	ExternalIdpID    *string    `db:"external_idp_id"`
	PasswordHash     *string    `db:"password_hash"`
	LastLoginAt      *time.Time `db:"last_login_at"`
	ServiceAccountID *string    `db:"service_account_id"`
	CreatedAt        time.Time  `db:"created_at"`
	UpdatedAt        time.Time  `db:"updated_at"`
	AllApplications  bool       `db:"all_applications"`
}

type IamPrincipalApplicationAccess struct {
	PrincipalID   string    `db:"principal_id"`
	ApplicationID string    `db:"application_id"`
	GrantedAt     time.Time `db:"granted_at"`
}

type IamPrincipalRole struct {
	PrincipalID      string    `db:"principal_id"`
	RoleName         string    `db:"role_name"`
	AssignmentSource *string   `db:"assignment_source"`
	AssignedAt       time.Time `db:"assigned_at"`
}

type IamRateLimitEvent struct {
	ID         int64     `db:"id"`
	Bucket     string    `db:"bucket"`
	Key        string    `db:"key"`
	OccurredAt time.Time `db:"occurred_at"`
}

type IamRefreshToken struct {
	ID                string     `db:"id"`
	TokenHash         string     `db:"token_hash"`
	PrincipalID       string     `db:"principal_id"`
	OauthClientID     *string    `db:"oauth_client_id"`
	Scopes            *string    `db:"scopes"`
	AccessibleClients *string    `db:"accessible_clients"`
	Revoked           bool       `db:"revoked"`
	RevokedAt         *time.Time `db:"revoked_at"`
	TokenFamily       *string    `db:"token_family"`
	ReplacedBy        *string    `db:"replaced_by"`
	CreatedAt         time.Time  `db:"created_at"`
	ExpiresAt         time.Time  `db:"expires_at"`
	LastUsedAt        *time.Time `db:"last_used_at"`
	CreatedFromIp     *string    `db:"created_from_ip"`
	UserAgent         *string    `db:"user_agent"`
}

type IamResetApprovalRequest struct {
	ID          string     `db:"id"`
	PrincipalID string     `db:"principal_id"`
	ClientID    *string    `db:"client_id"`
	Status      string     `db:"status"`
	Reset2fa    bool       `db:"reset_2fa"`
	Note        *string    `db:"note"`
	DecidedBy   *string    `db:"decided_by"`
	DecidedAt   *time.Time `db:"decided_at"`
	ExpiresAt   time.Time  `db:"expires_at"`
	CreatedAt   time.Time  `db:"created_at"`
}

type IamRole struct {
	ID              string    `db:"id"`
	ApplicationID   *string   `db:"application_id"`
	ApplicationCode *string   `db:"application_code"`
	Name            string    `db:"name"`
	DisplayName     string    `db:"display_name"`
	Description     *string   `db:"description"`
	Source          string    `db:"source"`
	ClientManaged   bool      `db:"client_managed"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
}

type IamRolePermission struct {
	RoleID     string `db:"role_id"`
	Permission string `db:"permission"`
}

type IamServiceAccount struct {
	ID                         string     `db:"id"`
	Code                       string     `db:"code"`
	Name                       string     `db:"name"`
	Description                *string    `db:"description"`
	ApplicationID              *string    `db:"application_id"`
	Active                     bool       `db:"active"`
	WhAuthType                 *string    `db:"wh_auth_type"`
	WhAuthTokenRef             *string    `db:"wh_auth_token_ref"`
	WhSigningSecretRef         *string    `db:"wh_signing_secret_ref"`
	WhSigningAlgorithm         *string    `db:"wh_signing_algorithm"`
	WhCredentialsCreatedAt     *time.Time `db:"wh_credentials_created_at"`
	WhCredentialsRegeneratedAt *time.Time `db:"wh_credentials_regenerated_at"`
	LastUsedAt                 *time.Time `db:"last_used_at"`
	CreatedAt                  time.Time  `db:"created_at"`
	UpdatedAt                  time.Time  `db:"updated_at"`
	Scope                      *string    `db:"scope"`
	ClientIds                  []string   `db:"client_ids"`
}

type IamUserMfaMethod struct {
	ID              string     `db:"id"`
	PrincipalID     string     `db:"principal_id"`
	Method          string     `db:"method"`
	SecretEncrypted *string    `db:"secret_encrypted"`
	ConfirmedAt     *time.Time `db:"confirmed_at"`
	LastUsedAt      *time.Time `db:"last_used_at"`
	CreatedAt       time.Time  `db:"created_at"`
}

type IamUserMfaRecoveryCode struct {
	ID          string     `db:"id"`
	PrincipalID string     `db:"principal_id"`
	CodeHash    string     `db:"code_hash"`
	UsedAt      *time.Time `db:"used_at"`
	CreatedAt   time.Time  `db:"created_at"`
}

type MsgConnection struct {
	ID               string    `db:"id"`
	Code             string    `db:"code"`
	Name             string    `db:"name"`
	Description      *string   `db:"description"`
	ExternalID       *string   `db:"external_id"`
	Status           string    `db:"status"`
	ServiceAccountID string    `db:"service_account_id"`
	ClientID         *string   `db:"client_id"`
	ClientIdentifier *string   `db:"client_identifier"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
}

type MsgDispatchJob struct {
	ID                 string          `db:"id"`
	ExternalID         *string         `db:"external_id"`
	Source             *string         `db:"source"`
	Kind               string          `db:"kind"`
	Code               string          `db:"code"`
	Subject            *string         `db:"subject"`
	EventID            *string         `db:"event_id"`
	CorrelationID      *string         `db:"correlation_id"`
	Metadata           json.RawMessage `db:"metadata"`
	TargetUrl          string          `db:"target_url"`
	Protocol           string          `db:"protocol"`
	Payload            *string         `db:"payload"`
	PayloadContentType *string         `db:"payload_content_type"`
	DataOnly           bool            `db:"data_only"`
	ServiceAccountID   *string         `db:"service_account_id"`
	ClientID           *string         `db:"client_id"`
	SubscriptionID     *string         `db:"subscription_id"`
	Mode               string          `db:"mode"`
	DispatchPoolID     *string         `db:"dispatch_pool_id"`
	MessageGroup       *string         `db:"message_group"`
	Sequence           int32           `db:"sequence"`
	TimeoutSeconds     int32           `db:"timeout_seconds"`
	SchemaID           *string         `db:"schema_id"`
	Status             string          `db:"status"`
	MaxRetries         int32           `db:"max_retries"`
	RetryStrategy      *string         `db:"retry_strategy"`
	ScheduledFor       *time.Time      `db:"scheduled_for"`
	ExpiresAt          *time.Time      `db:"expires_at"`
	AttemptCount       int32           `db:"attempt_count"`
	LastAttemptAt      *time.Time      `db:"last_attempt_at"`
	CompletedAt        *time.Time      `db:"completed_at"`
	DurationMillis     *int64          `db:"duration_millis"`
	LastError          *string         `db:"last_error"`
	IdempotencyKey     *string         `db:"idempotency_key"`
	CreatedAt          time.Time       `db:"created_at"`
	UpdatedAt          time.Time       `db:"updated_at"`
	ProjectedAt        *time.Time      `db:"projected_at"`
	QueuedAt           *time.Time      `db:"queued_at"`
}

type MsgDispatchJobAttempt struct {
	ID              string     `db:"id"`
	DispatchJobID   string     `db:"dispatch_job_id"`
	AttemptNumber   *int32     `db:"attempt_number"`
	Status          *string    `db:"status"`
	ResponseCode    *int32     `db:"response_code"`
	ResponseBody    *string    `db:"response_body"`
	ErrorMessage    *string    `db:"error_message"`
	ErrorStackTrace *string    `db:"error_stack_trace"`
	ErrorType       *string    `db:"error_type"`
	DurationMillis  *int64     `db:"duration_millis"`
	AttemptedAt     *time.Time `db:"attempted_at"`
	CompletedAt     *time.Time `db:"completed_at"`
	CreatedAt       time.Time  `db:"created_at"`
}

type MsgDispatchJobProjectionFeed struct {
	ID            int64           `db:"id"`
	DispatchJobID string          `db:"dispatch_job_id"`
	Operation     string          `db:"operation"`
	Payload       json.RawMessage `db:"payload"`
	CreatedAt     time.Time       `db:"created_at"`
	Processed     int16           `db:"processed"`
	ProcessedAt   *time.Time      `db:"processed_at"`
	ErrorMessage  *string         `db:"error_message"`
}

type MsgDispatchJobsRead struct {
	ID               string     `db:"id"`
	ExternalID       *string    `db:"external_id"`
	Source           *string    `db:"source"`
	Kind             string     `db:"kind"`
	Code             string     `db:"code"`
	Subject          *string    `db:"subject"`
	EventID          *string    `db:"event_id"`
	CorrelationID    *string    `db:"correlation_id"`
	TargetUrl        string     `db:"target_url"`
	Protocol         string     `db:"protocol"`
	ServiceAccountID *string    `db:"service_account_id"`
	ClientID         *string    `db:"client_id"`
	SubscriptionID   *string    `db:"subscription_id"`
	DispatchPoolID   *string    `db:"dispatch_pool_id"`
	Mode             string     `db:"mode"`
	MessageGroup     *string    `db:"message_group"`
	Sequence         *int32     `db:"sequence"`
	TimeoutSeconds   *int32     `db:"timeout_seconds"`
	Status           string     `db:"status"`
	MaxRetries       int32      `db:"max_retries"`
	RetryStrategy    *string    `db:"retry_strategy"`
	ScheduledFor     *time.Time `db:"scheduled_for"`
	ExpiresAt        *time.Time `db:"expires_at"`
	AttemptCount     int32      `db:"attempt_count"`
	LastAttemptAt    *time.Time `db:"last_attempt_at"`
	CompletedAt      *time.Time `db:"completed_at"`
	DurationMillis   *int64     `db:"duration_millis"`
	LastError        *string    `db:"last_error"`
	IdempotencyKey   *string    `db:"idempotency_key"`
	IsCompleted      *bool      `db:"is_completed"`
	IsTerminal       *bool      `db:"is_terminal"`
	Application      *string    `db:"application"`
	Subdomain        *string    `db:"subdomain"`
	Aggregate        *string    `db:"aggregate"`
	CreatedAt        time.Time  `db:"created_at"`
	UpdatedAt        time.Time  `db:"updated_at"`
	ProjectedAt      *time.Time `db:"projected_at"`
}

type MsgDispatchPool struct {
	ID               string    `db:"id"`
	Code             string    `db:"code"`
	Name             string    `db:"name"`
	Description      *string   `db:"description"`
	RateLimit        *int32    `db:"rate_limit"`
	Concurrency      int32     `db:"concurrency"`
	ClientID         *string   `db:"client_id"`
	ClientIdentifier *string   `db:"client_identifier"`
	Status           string    `db:"status"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
}

type MsgEvent struct {
	ID              string          `db:"id"`
	SpecVersion     *string         `db:"spec_version"`
	Type            string          `db:"type"`
	Source          string          `db:"source"`
	Subject         *string         `db:"subject"`
	Time            time.Time       `db:"time"`
	Data            json.RawMessage `db:"data"`
	CorrelationID   *string         `db:"correlation_id"`
	CausationID     *string         `db:"causation_id"`
	DeduplicationID *string         `db:"deduplication_id"`
	MessageGroup    *string         `db:"message_group"`
	ClientID        *string         `db:"client_id"`
	ContextData     json.RawMessage `db:"context_data"`
	CreatedAt       time.Time       `db:"created_at"`
	ProjectedAt     *time.Time      `db:"projected_at"`
	FannedOutAt     *time.Time      `db:"fanned_out_at"`
}

type MsgEventProjectionFeed struct {
	ID           int64           `db:"id"`
	EventID      string          `db:"event_id"`
	Payload      json.RawMessage `db:"payload"`
	CreatedAt    time.Time       `db:"created_at"`
	Processed    int16           `db:"processed"`
	ProcessedAt  *time.Time      `db:"processed_at"`
	ErrorMessage *string         `db:"error_message"`
}

type MsgEventType struct {
	ID           string    `db:"id"`
	Code         string    `db:"code"`
	Name         string    `db:"name"`
	Description  *string   `db:"description"`
	Status       string    `db:"status"`
	Source       string    `db:"source"`
	ClientScoped bool      `db:"client_scoped"`
	Application  string    `db:"application"`
	Subdomain    string    `db:"subdomain"`
	Aggregate    string    `db:"aggregate"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
	CreatedBy    *string   `db:"created_by"`
}

type MsgEventTypeSpecVersion struct {
	ID            string          `db:"id"`
	EventTypeID   string          `db:"event_type_id"`
	Version       string          `db:"version"`
	MimeType      string          `db:"mime_type"`
	SchemaContent json.RawMessage `db:"schema_content"`
	SchemaType    string          `db:"schema_type"`
	Status        string          `db:"status"`
	CreatedAt     time.Time       `db:"created_at"`
	UpdatedAt     time.Time       `db:"updated_at"`
}

type MsgEventsRead struct {
	ID              string    `db:"id"`
	SpecVersion     *string   `db:"spec_version"`
	Type            string    `db:"type"`
	Source          string    `db:"source"`
	Subject         *string   `db:"subject"`
	Time            time.Time `db:"time"`
	Data            *string   `db:"data"`
	CorrelationID   *string   `db:"correlation_id"`
	CausationID     *string   `db:"causation_id"`
	DeduplicationID *string   `db:"deduplication_id"`
	MessageGroup    *string   `db:"message_group"`
	ClientID        *string   `db:"client_id"`
	Application     *string   `db:"application"`
	Subdomain       *string   `db:"subdomain"`
	Aggregate       *string   `db:"aggregate"`
	ProjectedAt     time.Time `db:"projected_at"`
	CreatedAt       time.Time `db:"created_at"`
}

type MsgProcess struct {
	ID          string    `db:"id"`
	Code        string    `db:"code"`
	Name        string    `db:"name"`
	Description *string   `db:"description"`
	Status      string    `db:"status"`
	Source      string    `db:"source"`
	Application string    `db:"application"`
	Subdomain   string    `db:"subdomain"`
	ProcessName string    `db:"process_name"`
	Body        string    `db:"body"`
	DiagramType string    `db:"diagram_type"`
	Tags        []string  `db:"tags"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type MsgScheduledJob struct {
	ID                  string          `db:"id"`
	ClientID            *string         `db:"client_id"`
	Code                string          `db:"code"`
	Name                string          `db:"name"`
	Description         *string         `db:"description"`
	Status              string          `db:"status"`
	Crons               []string        `db:"crons"`
	Timezone            string          `db:"timezone"`
	Payload             json.RawMessage `db:"payload"`
	Concurrent          bool            `db:"concurrent"`
	TracksCompletion    bool            `db:"tracks_completion"`
	TimeoutSeconds      *int32          `db:"timeout_seconds"`
	DeliveryMaxAttempts int32           `db:"delivery_max_attempts"`
	TargetUrl           *string         `db:"target_url"`
	LastFiredAt         *time.Time      `db:"last_fired_at"`
	CreatedAt           time.Time       `db:"created_at"`
	UpdatedAt           time.Time       `db:"updated_at"`
	CreatedBy           *string         `db:"created_by"`
	UpdatedBy           *string         `db:"updated_by"`
	Version             int32           `db:"version"`
}

type MsgScheduledJobInstance struct {
	ID               string          `db:"id"`
	ScheduledJobID   string          `db:"scheduled_job_id"`
	ClientID         *string         `db:"client_id"`
	JobCode          string          `db:"job_code"`
	TriggerKind      string          `db:"trigger_kind"`
	ScheduledFor     *time.Time      `db:"scheduled_for"`
	FiredAt          time.Time       `db:"fired_at"`
	DeliveredAt      *time.Time      `db:"delivered_at"`
	CompletedAt      *time.Time      `db:"completed_at"`
	Status           string          `db:"status"`
	DeliveryAttempts int32           `db:"delivery_attempts"`
	DeliveryError    *string         `db:"delivery_error"`
	CompletionStatus *string         `db:"completion_status"`
	CompletionResult json.RawMessage `db:"completion_result"`
	CorrelationID    *string         `db:"correlation_id"`
	CreatedAt        time.Time       `db:"created_at"`
}

type MsgScheduledJobInstanceLog struct {
	ID             string          `db:"id"`
	InstanceID     string          `db:"instance_id"`
	ScheduledJobID *string         `db:"scheduled_job_id"`
	ClientID       *string         `db:"client_id"`
	Level          string          `db:"level"`
	Message        string          `db:"message"`
	Metadata       json.RawMessage `db:"metadata"`
	CreatedAt      time.Time       `db:"created_at"`
}

type MsgSubscription struct {
	ID               string    `db:"id"`
	Code             string    `db:"code"`
	ApplicationCode  *string   `db:"application_code"`
	Name             string    `db:"name"`
	Description      *string   `db:"description"`
	ClientID         *string   `db:"client_id"`
	ClientIdentifier *string   `db:"client_identifier"`
	ClientScoped     bool      `db:"client_scoped"`
	Target           string    `db:"target"`
	Queue            *string   `db:"queue"`
	Source           string    `db:"source"`
	Status           string    `db:"status"`
	MaxAgeSeconds    int32     `db:"max_age_seconds"`
	DispatchPoolID   *string   `db:"dispatch_pool_id"`
	DispatchPoolCode *string   `db:"dispatch_pool_code"`
	DelaySeconds     int32     `db:"delay_seconds"`
	Sequence         int32     `db:"sequence"`
	Mode             string    `db:"mode"`
	TimeoutSeconds   int32     `db:"timeout_seconds"`
	MaxRetries       int32     `db:"max_retries"`
	ServiceAccountID *string   `db:"service_account_id"`
	DataOnly         bool      `db:"data_only"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
	ConnectionID     *string   `db:"connection_id"`
	CreatedBy        *string   `db:"created_by"`
}

type MsgSubscriptionCustomConfig struct {
	ID             int32  `db:"id"`
	SubscriptionID string `db:"subscription_id"`
	ConfigKey      string `db:"config_key"`
	ConfigValue    string `db:"config_value"`
}

type MsgSubscriptionEventType struct {
	ID             int32   `db:"id"`
	SubscriptionID string  `db:"subscription_id"`
	EventTypeID    *string `db:"event_type_id"`
	EventTypeCode  string  `db:"event_type_code"`
	SpecVersion    *string `db:"spec_version"`
}

type OauthClient struct {
	ID                        string    `db:"id"`
	ClientID                  string    `db:"client_id"`
	ClientName                string    `db:"client_name"`
	ClientType                string    `db:"client_type"`
	ClientSecretRef           *string   `db:"client_secret_ref"`
	DefaultScopes             *string   `db:"default_scopes"`
	PkceRequired              bool      `db:"pkce_required"`
	ServiceAccountPrincipalID *string   `db:"service_account_principal_id"`
	Active                    bool      `db:"active"`
	CreatedAt                 time.Time `db:"created_at"`
	UpdatedAt                 time.Time `db:"updated_at"`
}

type OauthClientAllowedOrigin struct {
	OauthClientID string `db:"oauth_client_id"`
	AllowedOrigin string `db:"allowed_origin"`
}

type OauthClientApplicationID struct {
	OauthClientID string `db:"oauth_client_id"`
	ApplicationID string `db:"application_id"`
}

type OauthClientGrantType struct {
	OauthClientID string `db:"oauth_client_id"`
	GrantType     string `db:"grant_type"`
}

type OauthClientPostLogoutRedirectUri struct {
	OauthClientID         string `db:"oauth_client_id"`
	PostLogoutRedirectUri string `db:"post_logout_redirect_uri"`
}

type OauthClientRedirectUri struct {
	OauthClientID string `db:"oauth_client_id"`
	RedirectUri   string `db:"redirect_uri"`
}

type OauthIdentityProvider struct {
	ID                  string    `db:"id"`
	Code                string    `db:"code"`
	Name                string    `db:"name"`
	Type                string    `db:"type"`
	OidcIssuerUrl       *string   `db:"oidc_issuer_url"`
	OidcClientID        *string   `db:"oidc_client_id"`
	OidcClientSecretRef *string   `db:"oidc_client_secret_ref"`
	OidcMultiTenant     bool      `db:"oidc_multi_tenant"`
	OidcIssuerPattern   *string   `db:"oidc_issuer_pattern"`
	CreatedAt           time.Time `db:"created_at"`
	UpdatedAt           time.Time `db:"updated_at"`
}

type OauthIdentityProviderAllowedDomain struct {
	ID                 int32  `db:"id"`
	IdentityProviderID string `db:"identity_provider_id"`
	EmailDomain        string `db:"email_domain"`
}

type OauthIdpRoleMapping struct {
	ID               string    `db:"id"`
	IdpRoleName      string    `db:"idp_role_name"`
	InternalRoleName string    `db:"internal_role_name"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
	IdpType          *string   `db:"idp_type"`
}

type OauthOidcLoginState struct {
	State                    string    `db:"state"`
	EmailDomain              string    `db:"email_domain"`
	IdentityProviderID       string    `db:"identity_provider_id"`
	EmailDomainMappingID     string    `db:"email_domain_mapping_id"`
	Nonce                    string    `db:"nonce"`
	CodeVerifier             string    `db:"code_verifier"`
	ReturnUrl                *string   `db:"return_url"`
	OauthClientID            *string   `db:"oauth_client_id"`
	OauthRedirectUri         *string   `db:"oauth_redirect_uri"`
	OauthScope               *string   `db:"oauth_scope"`
	OauthState               *string   `db:"oauth_state"`
	OauthCodeChallenge       *string   `db:"oauth_code_challenge"`
	OauthCodeChallengeMethod *string   `db:"oauth_code_challenge_method"`
	OauthNonce               *string   `db:"oauth_nonce"`
	InteractionUid           *string   `db:"interaction_uid"`
	CreatedAt                time.Time `db:"created_at"`
	ExpiresAt                time.Time `db:"expires_at"`
}

type OauthOidcPayload struct {
	ID         string          `db:"id"`
	Type       string          `db:"type"`
	Payload    json.RawMessage `db:"payload"`
	GrantID    *string         `db:"grant_id"`
	UserCode   *string         `db:"user_code"`
	Uid        *string         `db:"uid"`
	ExpiresAt  *time.Time      `db:"expires_at"`
	ConsumedAt *time.Time      `db:"consumed_at"`
	CreatedAt  time.Time       `db:"created_at"`
}

type TntAnchorDomain struct {
	ID        string    `db:"id"`
	Domain    string    `db:"domain"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type TntClient struct {
	ID              string          `db:"id"`
	Name            string          `db:"name"`
	Identifier      string          `db:"identifier"`
	Status          string          `db:"status"`
	StatusReason    *string         `db:"status_reason"`
	StatusChangedAt *time.Time      `db:"status_changed_at"`
	Notes           json.RawMessage `db:"notes"`
	CreatedAt       time.Time       `db:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at"`
}

type TntClientAuthConfig struct {
	ID                  string          `db:"id"`
	EmailDomain         string          `db:"email_domain"`
	ConfigType          string          `db:"config_type"`
	PrimaryClientID     *string         `db:"primary_client_id"`
	AdditionalClientIds json.RawMessage `db:"additional_client_ids"`
	GrantedClientIds    json.RawMessage `db:"granted_client_ids"`
	AuthProvider        string          `db:"auth_provider"`
	OidcIssuerUrl       *string         `db:"oidc_issuer_url"`
	OidcClientID        *string         `db:"oidc_client_id"`
	OidcMultiTenant     bool            `db:"oidc_multi_tenant"`
	OidcIssuerPattern   *string         `db:"oidc_issuer_pattern"`
	OidcClientSecretRef *string         `db:"oidc_client_secret_ref"`
	CreatedAt           time.Time       `db:"created_at"`
	UpdatedAt           time.Time       `db:"updated_at"`
}

type TntCorsAllowedOrigin struct {
	ID          string    `db:"id"`
	Origin      string    `db:"origin"`
	Description *string   `db:"description"`
	CreatedBy   *string   `db:"created_by"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type TntEmailDomainMapping struct {
	ID                    string    `db:"id"`
	EmailDomain           string    `db:"email_domain"`
	IdentityProviderID    string    `db:"identity_provider_id"`
	ScopeType             string    `db:"scope_type"`
	PrimaryClientID       *string   `db:"primary_client_id"`
	RequiredOidcTenantID  *string   `db:"required_oidc_tenant_id"`
	SyncRolesFromIdp      bool      `db:"sync_roles_from_idp"`
	CreatedAt             time.Time `db:"created_at"`
	UpdatedAt             time.Time `db:"updated_at"`
	Require2fa            bool      `db:"require_2fa"`
	RememberDeviceEnabled bool      `db:"remember_device_enabled"`
	RememberDeviceDays    int32     `db:"remember_device_days"`
}

type TntEmailDomainMapping2faMethod struct {
	ID                   int32  `db:"id"`
	EmailDomainMappingID string `db:"email_domain_mapping_id"`
	Method               string `db:"method"`
}

type TntEmailDomainMappingAdditionalClient struct {
	ID                   int32  `db:"id"`
	EmailDomainMappingID string `db:"email_domain_mapping_id"`
	ClientID             string `db:"client_id"`
}

type TntEmailDomainMappingAllowedRole struct {
	ID                   int32  `db:"id"`
	EmailDomainMappingID string `db:"email_domain_mapping_id"`
	RoleID               string `db:"role_id"`
}

type TntEmailDomainMappingGrantedClient struct {
	ID                   int32  `db:"id"`
	EmailDomainMappingID string `db:"email_domain_mapping_id"`
	ClientID             string `db:"client_id"`
}

type WebauthnCredential struct {
	ID           string          `db:"id"`
	PrincipalID  string          `db:"principal_id"`
	CredentialID []byte          `db:"credential_id"`
	PasskeyData  json.RawMessage `db:"passkey_data"`
	Name         *string         `db:"name"`
	CreatedAt    time.Time       `db:"created_at"`
	LastUsedAt   *time.Time      `db:"last_used_at"`
}
