// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"encoding/json"
	"time"
)

type AppApplication struct {
	ID               string
	Type             string
	Code             string
	Name             string
	Description      *string
	IconUrl          *string
	Website          *string
	Logo             *string
	LogoMimeType     *string
	DefaultBaseUrl   *string
	ServiceAccountID *string
	Active           bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type AppApplicationOpenapiSpec struct {
	ID              string
	ApplicationID   string
	Version         string
	Status          string
	Spec            json.RawMessage
	SpecHash        string
	ChangeNotes     json.RawMessage
	ChangeNotesText *string
	SyncedAt        time.Time
	SyncedBy        *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AppClientConfig struct {
	ID            string
	ApplicationID string
	ClientID      string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AppPlatformConfig struct {
	ID              string
	ApplicationCode string
	Section         string
	Property        string
	Scope           string
	ClientID        *string
	ValueType       string
	Value           string
	Description     *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AppPlatformConfigAccess struct {
	ID              string
	ApplicationCode string
	RoleCode        string
	CanRead         bool
	CanWrite        bool
	CreatedAt       time.Time
}

type AudLog struct {
	ID            string
	EntityType    string
	EntityID      string
	Operation     string
	OperationJson json.RawMessage
	PrincipalID   *string
	PerformedAt   time.Time
	ApplicationID *string
	ClientID      *string
}

type IamAuthorizationCode struct {
	Code                string
	ClientID            string
	PrincipalID         string
	RedirectUri         string
	Scope               *string
	CodeChallenge       *string
	CodeChallengeMethod *string
	Nonce               *string
	State               *string
	ContextClientID     *string
	CreatedAt           time.Time
	ExpiresAt           time.Time
	Used                bool
}

type IamClientAccessGrant struct {
	ID          string
	PrincipalID string
	ClientID    string
	GrantedBy   string
	GrantedAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type IamLoginAttempt struct {
	ID            string
	AttemptType   string
	Outcome       string
	FailureReason *string
	Identifier    *string
	PrincipalID   *string
	IpAddress     *string
	UserAgent     *string
	AttemptedAt   time.Time
}

type IamMfaEmailPin struct {
	ID          string
	PrincipalID string
	Purpose     string
	PinHash     string
	Attempts    int32
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type IamMfaTrustedDevice struct {
	ID          string
	PrincipalID string
	TokenHash   string
	Label       *string
	ExpiresAt   time.Time
	CreatedAt   time.Time
	LastUsedAt  *time.Time
}

type IamOidcLoginState struct {
	State                    string
	EmailDomain              string
	AuthConfigID             string
	Nonce                    string
	CodeVerifier             string
	ReturnUrl                *string
	OauthClientID            *string
	OauthRedirectUri         *string
	OauthScope               *string
	OauthState               *string
	OauthCodeChallenge       *string
	OauthCodeChallengeMethod *string
	OauthNonce               *string
	CreatedAt                time.Time
	ExpiresAt                time.Time
}

type IamPasswordResetToken struct {
	ID          string
	PrincipalID string
	TokenHash   string
	ExpiresAt   time.Time
	CreatedAt   time.Time
	Purpose     string
	Reset2fa    bool
}

type IamPermission struct {
	ID          string
	Code        string
	Subdomain   string
	Context     string
	Aggregate   string
	Action      string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type IamPrincipal struct {
	ID               string
	Type             string
	Scope            *string
	ClientID         *string
	ApplicationID    *string
	Name             string
	Active           bool
	Email            *string
	EmailDomain      *string
	IdpType          *string
	ExternalIdpID    *string
	PasswordHash     *string
	LastLoginAt      *time.Time
	ServiceAccountID *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type IamPrincipalApplicationAccess struct {
	PrincipalID   string
	ApplicationID string
	GrantedAt     time.Time
}

type IamPrincipalRole struct {
	PrincipalID      string
	RoleName         string
	AssignmentSource *string
	AssignedAt       time.Time
}

type IamRateLimitEvent struct {
	ID         int64
	Bucket     string
	Key        string
	OccurredAt time.Time
}

type IamRefreshToken struct {
	ID                string
	TokenHash         string
	PrincipalID       string
	OauthClientID     *string
	Scopes            *string
	AccessibleClients *string
	Revoked           bool
	RevokedAt         *time.Time
	TokenFamily       *string
	ReplacedBy        *string
	CreatedAt         time.Time
	ExpiresAt         time.Time
	LastUsedAt        *time.Time
	CreatedFromIp     *string
	UserAgent         *string
}

type IamRole struct {
	ID              string
	ApplicationID   *string
	ApplicationCode *string
	Name            string
	DisplayName     string
	Description     *string
	Source          string
	ClientManaged   bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type IamRolePermission struct {
	RoleID     string
	Permission string
}

type IamServiceAccount struct {
	ID                         string
	Code                       string
	Name                       string
	Description                *string
	ApplicationID              *string
	Active                     bool
	WhAuthType                 *string
	WhAuthTokenRef             *string
	WhSigningSecretRef         *string
	WhSigningAlgorithm         *string
	WhCredentialsCreatedAt     *time.Time
	WhCredentialsRegeneratedAt *time.Time
	LastUsedAt                 *time.Time
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type IamUserMfaMethod struct {
	ID              string
	PrincipalID     string
	Method          string
	SecretEncrypted *string
	ConfirmedAt     *time.Time
	LastUsedAt      *time.Time
	CreatedAt       time.Time
}

type IamUserMfaRecoveryCode struct {
	ID          string
	PrincipalID string
	CodeHash    string
	UsedAt      *time.Time
	CreatedAt   time.Time
}

type MsgConnection struct {
	ID               string
	Code             string
	Name             string
	Description      *string
	ExternalID       *string
	Status           string
	ServiceAccountID string
	ClientID         *string
	ClientIdentifier *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type MsgDispatchJob struct {
	ID                 string
	ExternalID         *string
	Source             *string
	Kind               string
	Code               string
	Subject            *string
	EventID            *string
	CorrelationID      *string
	Metadata           json.RawMessage
	TargetUrl          string
	Protocol           string
	Payload            *string
	PayloadContentType *string
	DataOnly           bool
	ServiceAccountID   *string
	ClientID           *string
	SubscriptionID     *string
	Mode               string
	DispatchPoolID     *string
	MessageGroup       *string
	Sequence           int32
	TimeoutSeconds     int32
	SchemaID           *string
	Status             string
	MaxRetries         int32
	RetryStrategy      *string
	ScheduledFor       *time.Time
	ExpiresAt          *time.Time
	AttemptCount       int32
	LastAttemptAt      *time.Time
	CompletedAt        *time.Time
	DurationMillis     *int64
	LastError          *string
	IdempotencyKey     *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ProjectedAt        *time.Time
	QueuedAt           *time.Time
}

type MsgDispatchJobAttempt struct {
	ID              string
	DispatchJobID   string
	AttemptNumber   *int32
	Status          *string
	ResponseCode    *int32
	ResponseBody    *string
	ErrorMessage    *string
	ErrorStackTrace *string
	ErrorType       *string
	DurationMillis  *int64
	AttemptedAt     *time.Time
	CompletedAt     *time.Time
	CreatedAt       time.Time
}

type MsgDispatchJobProjectionFeed struct {
	ID            int64
	DispatchJobID string
	Operation     string
	Payload       json.RawMessage
	CreatedAt     time.Time
	Processed     int16
	ProcessedAt   *time.Time
	ErrorMessage  *string
}

type MsgDispatchJobsRead struct {
	ID               string
	ExternalID       *string
	Source           *string
	Kind             string
	Code             string
	Subject          *string
	EventID          *string
	CorrelationID    *string
	TargetUrl        string
	Protocol         string
	ServiceAccountID *string
	ClientID         *string
	SubscriptionID   *string
	DispatchPoolID   *string
	Mode             string
	MessageGroup     *string
	Sequence         *int32
	TimeoutSeconds   *int32
	Status           string
	MaxRetries       int32
	RetryStrategy    *string
	ScheduledFor     *time.Time
	ExpiresAt        *time.Time
	AttemptCount     int32
	LastAttemptAt    *time.Time
	CompletedAt      *time.Time
	DurationMillis   *int64
	LastError        *string
	IdempotencyKey   *string
	IsCompleted      *bool
	IsTerminal       *bool
	Application      *string
	Subdomain        *string
	Aggregate        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ProjectedAt      *time.Time
}

type MsgDispatchPool struct {
	ID               string
	Code             string
	Name             string
	Description      *string
	RateLimit        *int32
	Concurrency      int32
	ClientID         *string
	ClientIdentifier *string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type MsgEvent struct {
	ID              string
	SpecVersion     *string
	Type            string
	Source          string
	Subject         *string
	Time            time.Time
	Data            json.RawMessage
	CorrelationID   *string
	CausationID     *string
	DeduplicationID *string
	MessageGroup    *string
	ClientID        *string
	ContextData     json.RawMessage
	CreatedAt       time.Time
	ProjectedAt     *time.Time
	FannedOutAt     *time.Time
}

type MsgEventProjectionFeed struct {
	ID           int64
	EventID      string
	Payload      json.RawMessage
	CreatedAt    time.Time
	Processed    int16
	ProcessedAt  *time.Time
	ErrorMessage *string
}

type MsgEventType struct {
	ID           string
	Code         string
	Name         string
	Description  *string
	Status       string
	Source       string
	ClientScoped bool
	Application  string
	Subdomain    string
	Aggregate    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MsgEventTypeSpecVersion struct {
	ID            string
	EventTypeID   string
	Version       string
	MimeType      string
	SchemaContent json.RawMessage
	SchemaType    string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MsgEventsRead struct {
	ID              string
	SpecVersion     *string
	Type            string
	Source          string
	Subject         *string
	Time            time.Time
	Data            *string
	CorrelationID   *string
	CausationID     *string
	DeduplicationID *string
	MessageGroup    *string
	ClientID        *string
	Application     *string
	Subdomain       *string
	Aggregate       *string
	ProjectedAt     time.Time
	CreatedAt       time.Time
}

type MsgProcess struct {
	ID          string
	Code        string
	Name        string
	Description *string
	Status      string
	Source      string
	Application string
	Subdomain   string
	ProcessName string
	Body        string
	DiagramType string
	Tags        []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MsgScheduledJob struct {
	ID                  string
	ClientID            *string
	Code                string
	Name                string
	Description         *string
	Status              string
	Crons               []string
	Timezone            string
	Payload             json.RawMessage
	Concurrent          bool
	TracksCompletion    bool
	TimeoutSeconds      *int32
	DeliveryMaxAttempts int32
	TargetUrl           *string
	LastFiredAt         *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	CreatedBy           *string
	UpdatedBy           *string
	Version             int32
}

type MsgScheduledJobInstance struct {
	ID               string
	ScheduledJobID   string
	ClientID         *string
	JobCode          string
	TriggerKind      string
	ScheduledFor     *time.Time
	FiredAt          time.Time
	DeliveredAt      *time.Time
	CompletedAt      *time.Time
	Status           string
	DeliveryAttempts int32
	DeliveryError    *string
	CompletionStatus *string
	CompletionResult json.RawMessage
	CorrelationID    *string
	CreatedAt        time.Time
}

type MsgScheduledJobInstanceLog struct {
	ID             string
	InstanceID     string
	ScheduledJobID *string
	ClientID       *string
	Level          string
	Message        string
	Metadata       json.RawMessage
	CreatedAt      time.Time
}

type MsgSubscription struct {
	ID               string
	Code             string
	ApplicationCode  *string
	Name             string
	Description      *string
	ClientID         *string
	ClientIdentifier *string
	ClientScoped     bool
	Target           string
	Queue            *string
	Source           string
	Status           string
	MaxAgeSeconds    int32
	DispatchPoolID   *string
	DispatchPoolCode *string
	DelaySeconds     int32
	Sequence         int32
	Mode             string
	TimeoutSeconds   int32
	MaxRetries       int32
	ServiceAccountID *string
	DataOnly         bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ConnectionID     *string
}

type MsgSubscriptionCustomConfig struct {
	ID             int32
	SubscriptionID string
	ConfigKey      string
	ConfigValue    string
}

type MsgSubscriptionEventType struct {
	ID             int32
	SubscriptionID string
	EventTypeID    *string
	EventTypeCode  string
	SpecVersion    *string
}

type OauthClient struct {
	ID                        string
	ClientID                  string
	ClientName                string
	ClientType                string
	ClientSecretRef           *string
	DefaultScopes             *string
	PkceRequired              bool
	ServiceAccountPrincipalID *string
	Active                    bool
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type OauthClientAllowedOrigin struct {
	OauthClientID string
	AllowedOrigin string
}

type OauthClientApplicationID struct {
	OauthClientID string
	ApplicationID string
}

type OauthClientGrantType struct {
	OauthClientID string
	GrantType     string
}

type OauthClientPostLogoutRedirectUri struct {
	OauthClientID         string
	PostLogoutRedirectUri string
}

type OauthClientRedirectUri struct {
	OauthClientID string
	RedirectUri   string
}

type OauthIdentityProvider struct {
	ID                  string
	Code                string
	Name                string
	Type                string
	OidcIssuerUrl       *string
	OidcClientID        *string
	OidcClientSecretRef *string
	OidcMultiTenant     bool
	OidcIssuerPattern   *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type OauthIdentityProviderAllowedDomain struct {
	ID                 int32
	IdentityProviderID string
	EmailDomain        string
}

type OauthIdpRoleMapping struct {
	ID               string
	IdpRoleName      string
	InternalRoleName string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type OauthOidcLoginState struct {
	State                    string
	EmailDomain              string
	IdentityProviderID       string
	EmailDomainMappingID     string
	Nonce                    string
	CodeVerifier             string
	ReturnUrl                *string
	OauthClientID            *string
	OauthRedirectUri         *string
	OauthScope               *string
	OauthState               *string
	OauthCodeChallenge       *string
	OauthCodeChallengeMethod *string
	OauthNonce               *string
	InteractionUid           *string
	CreatedAt                time.Time
	ExpiresAt                time.Time
}

type OauthOidcPayload struct {
	ID         string
	Type       string
	Payload    json.RawMessage
	GrantID    *string
	UserCode   *string
	Uid        *string
	ExpiresAt  *time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type TntAnchorDomain struct {
	ID        string
	Domain    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TntClient struct {
	ID              string
	Name            string
	Identifier      string
	Status          string
	StatusReason    *string
	StatusChangedAt *time.Time
	Notes           json.RawMessage
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TntClientAuthConfig struct {
	ID                  string
	EmailDomain         string
	ConfigType          string
	PrimaryClientID     *string
	AdditionalClientIds json.RawMessage
	GrantedClientIds    json.RawMessage
	AuthProvider        string
	OidcIssuerUrl       *string
	OidcClientID        *string
	OidcMultiTenant     bool
	OidcIssuerPattern   *string
	OidcClientSecretRef *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type TntCorsAllowedOrigin struct {
	ID          string
	Origin      string
	Description *string
	CreatedBy   *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TntEmailDomainMapping struct {
	ID                    string
	EmailDomain           string
	IdentityProviderID    string
	ScopeType             string
	PrimaryClientID       *string
	RequiredOidcTenantID  *string
	SyncRolesFromIdp      bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Require2fa            bool
	RememberDeviceEnabled bool
	RememberDeviceDays    int32
}

type TntEmailDomainMapping2faMethod struct {
	ID                   int32
	EmailDomainMappingID string
	Method               string
}

type TntEmailDomainMappingAdditionalClient struct {
	ID                   int32
	EmailDomainMappingID string
	ClientID             string
}

type TntEmailDomainMappingAllowedRole struct {
	ID                   int32
	EmailDomainMappingID string
	RoleID               string
}

type TntEmailDomainMappingGrantedClient struct {
	ID                   int32
	EmailDomainMappingID string
	ClientID             string
}

type WebauthnCredential struct {
	ID           string
	PrincipalID  string
	CredentialID []byte
	PasskeyData  json.RawMessage
	Name         *string
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}
