// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"
	"encoding/json"
)

type Querier interface {
	AnchorDomainDelete(ctx context.Context, id string) error
	AnchorDomainFindAll(ctx context.Context) ([]TntAnchorDomain, error)
	AnchorDomainFindByDomain(ctx context.Context, domain string) (TntAnchorDomain, error)
	// ── AnchorDomain (tnt_anchor_domains) ────────────────────────────────
	AnchorDomainFindByID(ctx context.Context, id string) (TntAnchorDomain, error)
	AnchorDomainUpsert(ctx context.Context, arg AnchorDomainUpsertParams) error
	ApplicationDelete(ctx context.Context, id string) error
	ApplicationFindByCode(ctx context.Context, code string) (AppApplication, error)
	// Queries for app_applications.
	ApplicationFindByID(ctx context.Context, id string) (AppApplication, error)
	ApplicationUpsert(ctx context.Context, arg ApplicationUpsertParams) error
	// Queries for aud_logs (read-only — writes happen in platformsink).
	AuditFindByID(ctx context.Context, id string) (AuditFindByIDRow, error)
	// All filters are optional via the IS-NULL-OR pattern. Limit + offset
	// are always bound. Ordered by most recent first.
	AuditFindWithFilters(ctx context.Context, arg AuditFindWithFiltersParams) ([]AuditFindWithFiltersRow, error)
	ClientAuthConfigDelete(ctx context.Context, id string) error
	ClientAuthConfigFindAll(ctx context.Context) ([]TntClientAuthConfig, error)
	ClientAuthConfigFindByEmailDomain(ctx context.Context, emailDomain string) (TntClientAuthConfig, error)
	// ── ClientAuthConfig (tnt_client_auth_configs) ───────────────────────
	ClientAuthConfigFindByID(ctx context.Context, id string) (TntClientAuthConfig, error)
	ClientAuthConfigUpsert(ctx context.Context, arg ClientAuthConfigUpsertParams) error
	ClientConfigDelete(ctx context.Context, id string) error
	ClientConfigFindByApp(ctx context.Context, applicationID string) ([]AppClientConfig, error)
	ClientConfigFindByAppAndClient(ctx context.Context, arg ClientConfigFindByAppAndClientParams) (AppClientConfig, error)
	ClientConfigFindByClient(ctx context.Context, clientID string) ([]AppClientConfig, error)
	ClientConfigUpsert(ctx context.Context, arg ClientConfigUpsertParams) error
	ClientDelete(ctx context.Context, id string) error
	ClientFindAll(ctx context.Context) ([]TntClient, error)
	// All queries operating on tnt_clients. The Repository wrapper in
	// internal/platform/client maps the generated row type onto the
	// aggregate's Client struct.
	ClientFindByID(ctx context.Context, id string) (TntClient, error)
	ClientFindByIdentifier(ctx context.Context, identifier string) (TntClient, error)
	ClientSearch(ctx context.Context, pattern string) ([]TntClient, error)
	ClientUpsert(ctx context.Context, arg ClientUpsertParams) error
	ConnectionDelete(ctx context.Context, id string) error
	ConnectionFindAll(ctx context.Context) ([]MsgConnection, error)
	ConnectionFindByCodeAnchor(ctx context.Context, code string) (MsgConnection, error)
	ConnectionFindByCodeClient(ctx context.Context, arg ConnectionFindByCodeClientParams) (MsgConnection, error)
	// Queries for msg_connections.
	ConnectionFindByID(ctx context.Context, id string) (MsgConnection, error)
	ConnectionUpsert(ctx context.Context, arg ConnectionUpsertParams) error
	CorsOriginDelete(ctx context.Context, id string) error
	CorsOriginFindAll(ctx context.Context) ([]TntCorsAllowedOrigin, error)
	// Queries for tnt_cors_allowed_origins. Simple single-table CRUD.
	CorsOriginFindByID(ctx context.Context, id string) (TntCorsAllowedOrigin, error)
	CorsOriginFindByOrigin(ctx context.Context, origin string) (TntCorsAllowedOrigin, error)
	CorsOriginListStrings(ctx context.Context) ([]string, error)
	CorsOriginUpsert(ctx context.Context, arg CorsOriginUpsertParams) error
	// One row per delivery attempt. The schema column `status` stores the
	// attempt outcome (`SUCCESS` / `FAILURE`); the entity exposes a
	// derived `success` bool to match the Rust wire shape.
	DispatchJobAttemptInsert(ctx context.Context, arg DispatchJobAttemptInsertParams) error
	DispatchJobAttemptsByJob(ctx context.Context, dispatchJobID string) ([]DispatchJobAttemptsByJobRow, error)
	DispatchJobFindByEventID(ctx context.Context, eventID *string) ([]DispatchJobFindByEventIDRow, error)
	DispatchJobFindByExternalID(ctx context.Context, externalID *string) (DispatchJobFindByExternalIDRow, error)
	// Queries for msg_dispatch_jobs + msg_dispatch_job_attempts. The
	// column set matches the post-019 (partitioned) schema. Composite PK
	// is (id, created_at); claim queries use FOR UPDATE SKIP LOCKED so
	// multiple scheduler nodes can run against the same DB without
	// contention.
	//
	// FindWithFilters + DistinctValues stay hand-rolled in repository.go
	// (dynamic WHERE + dynamic column names) — sqlc can't generate those
	// without a query per filter combination.
	//
	// InsertBatch also stays in repository.go via pgx.Batch — sqlc has no
	// batch wrapper for partial-failure-tolerant UNNEST inserts.
	DispatchJobFindByID(ctx context.Context, id string) (DispatchJobFindByIDRow, error)
	// Used by the scheduler's PendingJobPoller. FOR UPDATE SKIP LOCKED so
	// the claim works concurrently across scheduler nodes. Filter on
	// scheduled_for skips retries not yet due.
	DispatchJobFindPendingForPool(ctx context.Context, arg DispatchJobFindPendingForPoolParams) ([]DispatchJobFindPendingForPoolRow, error)
	DispatchJobInsert(ctx context.Context, arg DispatchJobInsertParams) error
	// Status → COMPLETED. Stamps completed_at + duration_millis.
	DispatchJobMarkCompleted(ctx context.Context, arg DispatchJobMarkCompletedParams) error
	// Terminal failure. Stamps last_error + completed_at + duration_millis.
	DispatchJobMarkFailed(ctx context.Context, arg DispatchJobMarkFailedParams) error
	// Status → PROCESSING. Stamps last_attempt_at. Called by the router
	// immediately before the first delivery attempt.
	DispatchJobMarkInProgress(ctx context.Context, arg DispatchJobMarkInProgressParams) error
	// Bumps attempt_count + stamps scheduled_for so the next poll picks
	// it up once due. Status stays PENDING.
	DispatchJobScheduleRetry(ctx context.Context, arg DispatchJobScheduleRetryParams) error
	DispatchPoolDelete(ctx context.Context, id string) error
	DispatchPoolFindAll(ctx context.Context) ([]MsgDispatchPool, error)
	DispatchPoolFindByCodeAnchor(ctx context.Context, code string) (MsgDispatchPool, error)
	DispatchPoolFindByCodeClient(ctx context.Context, arg DispatchPoolFindByCodeClientParams) (MsgDispatchPool, error)
	// Queries for msg_dispatch_pools.
	DispatchPoolFindByID(ctx context.Context, id string) (MsgDispatchPool, error)
	DispatchPoolUpsert(ctx context.Context, arg DispatchPoolUpsertParams) error
	EmailDomainMapping2FAMethodInsert(ctx context.Context, arg EmailDomainMapping2FAMethodInsertParams) error
	EmailDomainMapping2FAMethodsClear(ctx context.Context, emailDomainMappingID string) error
	EmailDomainMapping2FAMethodsForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMapping2FAMethodsForMappingsRow, error)
	EmailDomainMappingAdditionalClientInsert(ctx context.Context, arg EmailDomainMappingAdditionalClientInsertParams) error
	// ── junctions: clear + insert ─────────────────────────────────────────
	EmailDomainMappingAdditionalClientsClear(ctx context.Context, emailDomainMappingID string) error
	// ── junctions: batch hydrate via ANY($1) ─────────────────────────────
	EmailDomainMappingAdditionalClientsForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMappingAdditionalClientsForMappingsRow, error)
	EmailDomainMappingAllowedRoleInsert(ctx context.Context, arg EmailDomainMappingAllowedRoleInsertParams) error
	EmailDomainMappingAllowedRolesClear(ctx context.Context, emailDomainMappingID string) error
	EmailDomainMappingAllowedRolesForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMappingAllowedRolesForMappingsRow, error)
	EmailDomainMappingDelete(ctx context.Context, id string) error
	EmailDomainMappingFindAll(ctx context.Context) ([]TntEmailDomainMapping, error)
	EmailDomainMappingFindByDomain(ctx context.Context, emailDomain string) (TntEmailDomainMapping, error)
	// Queries for tnt_email_domain_mappings + its junction tables
	// (additional_clients, granted_clients, allowed_roles, 2fa_methods).
	// None of the junctions declare FK ON DELETE CASCADE, so Delete must
	// clean them explicitly. Mirrors the Rust impl (2fa_methods is Go-only).
	EmailDomainMappingFindByID(ctx context.Context, id string) (TntEmailDomainMapping, error)
	EmailDomainMappingGrantedClientInsert(ctx context.Context, arg EmailDomainMappingGrantedClientInsertParams) error
	EmailDomainMappingGrantedClientsClear(ctx context.Context, emailDomainMappingID string) error
	EmailDomainMappingGrantedClientsForMappings(ctx context.Context, dollar_1 []string) ([]EmailDomainMappingGrantedClientsForMappingsRow, error)
	EmailDomainMappingUpsert(ctx context.Context, arg EmailDomainMappingUpsertParams) error
	EventTypeDelete(ctx context.Context, id string) error
	EventTypeFindByApplication(ctx context.Context, application string) ([]MsgEventType, error)
	EventTypeFindByCode(ctx context.Context, code string) (MsgEventType, error)
	// Queries for msg_event_types + msg_event_type_spec_versions.
	// Two upsert variants: ON CONFLICT (id) for the canonical path, and
	// ON CONFLICT (code) for the sync use case which keys by code.
	EventTypeFindByID(ctx context.Context, id string) (MsgEventType, error)
	EventTypeUpsertByCode(ctx context.Context, arg EventTypeUpsertByCodeParams) error
	EventTypeUpsertByID(ctx context.Context, arg EventTypeUpsertByIDParams) error
	IdentityProviderDelete(ctx context.Context, id string) error
	IdentityProviderDomainInsert(ctx context.Context, arg IdentityProviderDomainInsertParams) error
	IdentityProviderDomainsClear(ctx context.Context, identityProviderID string) error
	IdentityProviderDomainsForIDPs(ctx context.Context, idpIds []string) ([]IdentityProviderDomainsForIDPsRow, error)
	IdentityProviderFindAll(ctx context.Context) ([]OauthIdentityProvider, error)
	IdentityProviderFindByCode(ctx context.Context, code string) (OauthIdentityProvider, error)
	// Queries for oauth_identity_providers + oauth_identity_provider_allowed_domains.
	// Email domains are stored in the junction table (one row per allowed domain),
	// not as a column on the parent — the previous Go port incorrectly treated
	// this as a single JSONB-style column.
	IdentityProviderFindByID(ctx context.Context, id string) (OauthIdentityProvider, error)
	IdentityProviderUpsert(ctx context.Context, arg IdentityProviderUpsertParams) error
	IdpRoleMappingDelete(ctx context.Context, id string) error
	IdpRoleMappingFindAll(ctx context.Context) ([]OauthIdpRoleMapping, error)
	// ── IdpRoleMapping (oauth_idp_role_mappings) ─────────────────────────
	// Schema columns: id, idp_role_name, internal_role_name, created_at,
	// updated_at. The Go entity carries an `IdpType` field that has no
	// backing column today (matches Rust, where the column was dropped);
	// the field is ignored on persist and reads back as "".
	IdpRoleMappingFindByID(ctx context.Context, id string) (OauthIdpRoleMapping, error)
	IdpRoleMappingFindByIdpRole(ctx context.Context, idpRoleName string) ([]OauthIdpRoleMapping, error)
	IdpRoleMappingUpsert(ctx context.Context, arg IdpRoleMappingUpsertParams) error
	OAuthClientDelete(ctx context.Context, id string) error
	OAuthClientFindAll(ctx context.Context) ([]OauthClient, error)
	OAuthClientFindByClientID(ctx context.Context, clientID string) (OauthClient, error)
	// Queries for the auth subdomain: OAuthClient + AnchorDomain +
	// ClientAuthConfig + IdpRoleMapping aggregates.
	// ── OAuthClient (oauth_clients + 2 junctions wired today) ────────────
	// The schema also has 3 more junctions (post_logout_redirect_uris,
	// allowed_origins, application_ids) that the Go entity doesn't carry
	// yet — they're a follow-up alongside the entity extension.
	// The Go entity stores Argon2-hashed secrets in client_secret_ref
	// (Rust uses it as a secrets-manager reference; Go uses it as the
	// hash). See HANDOFF.md §4 for the planned PHC-salt fix.
	OAuthClientFindByID(ctx context.Context, id string) (OauthClient, error)
	OAuthClientGrantTypeInsert(ctx context.Context, arg OAuthClientGrantTypeInsertParams) error
	OAuthClientGrantTypesClear(ctx context.Context, oauthClientID string) error
	OAuthClientGrantTypesForClient(ctx context.Context, oauthClientID string) ([]string, error)
	OAuthClientGrantTypesForClients(ctx context.Context, dollar_1 []string) ([]OauthClientGrantType, error)
	OAuthClientRedirectURIInsert(ctx context.Context, arg OAuthClientRedirectURIInsertParams) error
	OAuthClientRedirectURIsClear(ctx context.Context, oauthClientID string) error
	OAuthClientRedirectURIsForClient(ctx context.Context, oauthClientID string) ([]string, error)
	OAuthClientRedirectURIsForClients(ctx context.Context, dollar_1 []string) ([]OauthClientRedirectUri, error)
	OAuthClientUpsert(ctx context.Context, arg OAuthClientUpsertParams) error
	OAuthPayloadDelete(ctx context.Context, id string) error
	OAuthPayloadDeleteByGrant(ctx context.Context, grantID *string) error
	OAuthPayloadFindByID(ctx context.Context, arg OAuthPayloadFindByIDParams) (OauthOidcPayload, error)
	// Queries for oauth_oidc_payloads — the OIDC artifact store
	// (access/refresh tokens, authorization codes, PKCE sessions, etc.).
	// Webauthn ceremonies use this same table; their queries live in
	// webauthn_ceremony.sql so each subsystem owns its own slice.
	OAuthPayloadInsert(ctx context.Context, arg OAuthPayloadInsertParams) error
	OAuthPayloadMarkConsumed(ctx context.Context, id string) error
	OAuthPayloadPurgeExpired(ctx context.Context) (int64, error)
	PermissionDeleteByCode(ctx context.Context, code string) error
	PermissionFindAll(ctx context.Context) ([]IamPermission, error)
	PermissionFindByCode(ctx context.Context, code string) (IamPermission, error)
	PlatformConfigAccessDelete(ctx context.Context, id string) error
	PlatformConfigAccessFindByApplication(ctx context.Context, applicationCode string) ([]AppPlatformConfigAccess, error)
	PlatformConfigAccessFindByID(ctx context.Context, id string) (AppPlatformConfigAccess, error)
	PlatformConfigAccessFindByRole(ctx context.Context, arg PlatformConfigAccessFindByRoleParams) (AppPlatformConfigAccess, error)
	PlatformConfigAccessHasReadByRoles(ctx context.Context, arg PlatformConfigAccessHasReadByRolesParams) (bool, error)
	PlatformConfigAccessHasWriteByRoles(ctx context.Context, arg PlatformConfigAccessHasWriteByRolesParams) (bool, error)
	PlatformConfigAccessUpsert(ctx context.Context, arg PlatformConfigAccessUpsertParams) error
	PlatformConfigDelete(ctx context.Context, id string) error
	PlatformConfigFindByApplication(ctx context.Context, applicationCode string) ([]AppPlatformConfig, error)
	PlatformConfigFindByCoordinateAnchor(ctx context.Context, arg PlatformConfigFindByCoordinateAnchorParams) (AppPlatformConfig, error)
	PlatformConfigFindByCoordinateClient(ctx context.Context, arg PlatformConfigFindByCoordinateClientParams) (AppPlatformConfig, error)
	// Queries for app_platform_configs + app_platform_config_access. Two
	// entity types, one repo (mirroring the Rust shape).
	PlatformConfigFindByID(ctx context.Context, id string) (AppPlatformConfig, error)
	PlatformConfigUpsert(ctx context.Context, arg PlatformConfigUpsertParams) error
	// iam_principal_application_access + iam_client_access_grants do NOT have
	// FK ON DELETE CASCADE on principal_id (only iam_principal_roles does), so
	// Delete has to clean them explicitly. Mirrors Rust's delete() + Persist::delete.
	PrincipalApplicationAccessClear(ctx context.Context, principalID string) error
	PrincipalClientAccessGrantsClear(ctx context.Context, principalID string) error
	PrincipalDelete(ctx context.Context, id string) error
	PrincipalFindAll(ctx context.Context) ([]IamPrincipal, error)
	// Case-insensitive match: emails are stored lower-cased (see repository.Persist),
	// but callers pass values from sources whose casing we don't control (OIDC
	// tokens, the login form). LOWER(email) also finds any legacy mixed-case row so
	// the login self-heal can normalise it. The repo lower-cases $1 before binding.
	PrincipalFindByEmail(ctx context.Context, email *string) (IamPrincipal, error)
	// Queries for iam_principals + junction tables.
	//
	// The schema stores user-identity fields as flat columns (email, email_domain,
	// idp_type, external_idp_id, password_hash, last_login_at) rather than the
	// JSONB blobs the Go entity carries. Mapping happens in repository.go.
	PrincipalFindByID(ctx context.Context, id string) (IamPrincipal, error)
	PrincipalFindByServiceAccount(ctx context.Context, serviceAccountID *string) (IamPrincipal, error)
	PrincipalUpsert(ctx context.Context, arg PrincipalUpsertParams) error
	ProcessDelete(ctx context.Context, id string) error
	ProcessFindByCode(ctx context.Context, code string) (MsgProcess, error)
	// Queries for msg_processes. The schema has no created_by column —
	// matches the Rust source which hard-codes CreatedBy: None on read.
	ProcessFindByID(ctx context.Context, id string) (MsgProcess, error)
	ProcessUpsert(ctx context.Context, arg ProcessUpsertParams) error
	RoleApplicationCodes(ctx context.Context) ([]*string, error)
	RoleCountAssignments(ctx context.Context, roleName string) (int64, error)
	RoleDelete(ctx context.Context, id string) error
	RoleFindAll(ctx context.Context) ([]IamRole, error)
	RoleFindByApplicationID(ctx context.Context, applicationID *string) ([]IamRole, error)
	// Queries for iam_roles + iam_role_permissions. Permissions are
	// many-to-many; Persist replaces them wholesale.
	RoleFindByID(ctx context.Context, id string) (IamRole, error)
	RoleFindByName(ctx context.Context, name string) (IamRole, error)
	RoleFindBySource(ctx context.Context, source string) ([]IamRole, error)
	RolePermissionInsert(ctx context.Context, arg RolePermissionInsertParams) error
	RolePermissionsClear(ctx context.Context, roleID string) error
	RolePermissionsForRoles(ctx context.Context, roleIds []string) ([]IamRolePermission, error)
	RoleUpsert(ctx context.Context, arg RoleUpsertParams) error
	ScheduledJobDelete(ctx context.Context, id string) error
	ScheduledJobFindActive(ctx context.Context) ([]MsgScheduledJob, error)
	ScheduledJobFindAll(ctx context.Context) ([]MsgScheduledJob, error)
	ScheduledJobFindByCodeClient(ctx context.Context, arg ScheduledJobFindByCodeClientParams) (MsgScheduledJob, error)
	ScheduledJobFindByCodePlatform(ctx context.Context, code string) (MsgScheduledJob, error)
	// Queries for msg_scheduled_jobs. Schema (migration 021) matches the
	// Go entity 1:1 — straightforward port.
	ScheduledJobFindByID(ctx context.Context, id string) (MsgScheduledJob, error)
	ScheduledJobUpsert(ctx context.Context, arg ScheduledJobUpsertParams) error
	ServiceAccountDelete(ctx context.Context, id string) error
	ServiceAccountFindAll(ctx context.Context) ([]IamServiceAccount, error)
	ServiceAccountFindByCode(ctx context.Context, code string) (IamServiceAccount, error)
	// Queries for iam_service_accounts. Webhook credentials are stored as
	// separate columns (wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
	// wh_signing_algorithm) matching Rust. The repository maps the flat
	// columns into a single WebhookCredentials struct in the aggregate.
	ServiceAccountFindByID(ctx context.Context, id string) (IamServiceAccount, error)
	ServiceAccountUpsert(ctx context.Context, arg ServiceAccountUpsertParams) error
	SpecVersionUpsert(ctx context.Context, arg SpecVersionUpsertParams) error
	SpecVersionsClear(ctx context.Context, eventTypeID string) error
	SpecVersionsForEventTypes(ctx context.Context, eventTypeIds []string) ([]MsgEventTypeSpecVersion, error)
	SubscriptionConfigInsert(ctx context.Context, arg SubscriptionConfigInsertParams) error
	SubscriptionConfigsClear(ctx context.Context, subscriptionID string) error
	SubscriptionConfigsForSubs(ctx context.Context, subscriptionIds []string) ([]SubscriptionConfigsForSubsRow, error)
	SubscriptionDelete(ctx context.Context, id string) error
	SubscriptionEventTypeInsert(ctx context.Context, arg SubscriptionEventTypeInsertParams) error
	SubscriptionEventTypesClear(ctx context.Context, subscriptionID string) error
	SubscriptionEventTypesForSubs(ctx context.Context, subscriptionIds []string) ([]SubscriptionEventTypesForSubsRow, error)
	SubscriptionFindAll(ctx context.Context) ([]MsgSubscription, error)
	SubscriptionFindByCodeAnchor(ctx context.Context, code string) (MsgSubscription, error)
	SubscriptionFindByCodeClient(ctx context.Context, arg SubscriptionFindByCodeClientParams) (MsgSubscription, error)
	// Queries for msg_subscriptions + msg_subscription_event_types +
	// msg_subscription_custom_configs.
	//
	// Schema columns differ from the previous Go port in several places:
	//   - target (not endpoint)
	//   - msg_subscription_event_types has no filter column
	//   - msg_subscription_custom_configs uses config_key/config_value (not key/value)
	//   - no created_by column on msg_subscriptions
	// All of these were silent runtime bugs in the pre-sqlc repo.
	SubscriptionFindByID(ctx context.Context, id string) (MsgSubscription, error)
	SubscriptionUpsert(ctx context.Context, arg SubscriptionUpsertParams) error
	WebauthnCeremonyConsume(ctx context.Context, id string) (json.RawMessage, error)
	WebauthnCeremonyPurgeExpired(ctx context.Context, arg WebauthnCeremonyPurgeExpiredParams) (int64, error)
	// Queries for WebAuthn ceremony state in oauth_oidc_payloads.
	// The id column carries a type prefix ("WebauthnRegistration:{stateID}")
	// to keep ids unique across the shared store; the type column carries
	// the same discriminant. Mirrors the Rust impl.
	WebauthnCeremonyUpsert(ctx context.Context, arg WebauthnCeremonyUpsertParams) error
	WebauthnCredentialDelete(ctx context.Context, id string) error
	WebauthnCredentialFindByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error)
	// Queries for webauthn_credentials.
	// Column is passkey_data (JSONB), not "credential" — the entity field
	// name and the column name differ.
	WebauthnCredentialFindByID(ctx context.Context, id string) (WebauthnCredential, error)
	WebauthnCredentialFindByPrincipal(ctx context.Context, principalID string) ([]WebauthnCredential, error)
	WebauthnCredentialUpsert(ctx context.Context, arg WebauthnCredentialUpsertParams) error
}

var _ Querier = (*Queries)(nil)
