// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serviceaccount.sql

package dbq

import (
	"context"
	"time"
)

const serviceAccountDelete = `-- name: ServiceAccountDelete :exec
DELETE FROM iam_service_accounts WHERE id = $1
`

func (q *Queries) ServiceAccountDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, serviceAccountDelete, id)
	return err
}

const serviceAccountFindAll = `-- name: ServiceAccountFindAll :many
SELECT id, code, name, description, application_id, active,
       wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
       wh_signing_algorithm, wh_credentials_created_at,
       wh_credentials_regenerated_at, last_used_at, created_at, updated_at,
       scope, client_ids
FROM iam_service_accounts
ORDER BY code
`

func (q *Queries) ServiceAccountFindAll(ctx context.Context) ([]IamServiceAccount, error) {
	rows, err := q.db.Query(ctx, serviceAccountFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamServiceAccount{}
	for rows.Next() {
		var i IamServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ApplicationID,
			&i.Active,
			&i.WhAuthType,
			&i.WhAuthTokenRef,
			&i.WhSigningSecretRef,
			&i.WhSigningAlgorithm,
			&i.WhCredentialsCreatedAt,
			&i.WhCredentialsRegeneratedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.ClientIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceAccountFindByCode = `-- name: ServiceAccountFindByCode :one
SELECT id, code, name, description, application_id, active,
       wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
       wh_signing_algorithm, wh_credentials_created_at,
       wh_credentials_regenerated_at, last_used_at, created_at, updated_at,
       scope, client_ids
FROM iam_service_accounts
WHERE code = $1
`

func (q *Queries) ServiceAccountFindByCode(ctx context.Context, code string) (IamServiceAccount, error) {
	row := q.db.QueryRow(ctx, serviceAccountFindByCode, code)
	var i IamServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ApplicationID,
		&i.Active,
		&i.WhAuthType,
		&i.WhAuthTokenRef,
		&i.WhSigningSecretRef,
		&i.WhSigningAlgorithm,
		&i.WhCredentialsCreatedAt,
		&i.WhCredentialsRegeneratedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.ClientIds,
	)
	return i, err
}

const serviceAccountFindByID = `-- name: ServiceAccountFindByID :one

SELECT id, code, name, description, application_id, active,
       wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
       wh_signing_algorithm, wh_credentials_created_at,
       wh_credentials_regenerated_at, last_used_at, created_at, updated_at,
       scope, client_ids
FROM iam_service_accounts
WHERE id = $1
`

// Queries for iam_service_accounts. Webhook credentials are stored as
// separate columns (wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
// wh_signing_algorithm) matching Rust. The repository maps the flat
// columns into a single WebhookCredentials struct in the aggregate.
func (q *Queries) ServiceAccountFindByID(ctx context.Context, id string) (IamServiceAccount, error) {
	row := q.db.QueryRow(ctx, serviceAccountFindByID, id)
	var i IamServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ApplicationID,
		&i.Active,
		&i.WhAuthType,
		&i.WhAuthTokenRef,
		&i.WhSigningSecretRef,
		&i.WhSigningAlgorithm,
		&i.WhCredentialsCreatedAt,
		&i.WhCredentialsRegeneratedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.ClientIds,
	)
	return i, err
}

const serviceAccountUpsert = `-- name: ServiceAccountUpsert :exec
INSERT INTO iam_service_accounts
    (id, code, name, description, application_id, scope, client_ids, active,
     wh_auth_type, wh_auth_token_ref, wh_signing_secret_ref,
     wh_signing_algorithm, wh_credentials_created_at,
     wh_credentials_regenerated_at, last_used_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    application_id = EXCLUDED.application_id,
    scope = EXCLUDED.scope,
    client_ids = EXCLUDED.client_ids,
    active = EXCLUDED.active,
    wh_auth_type = EXCLUDED.wh_auth_type,
    wh_auth_token_ref = EXCLUDED.wh_auth_token_ref,
    wh_signing_secret_ref = EXCLUDED.wh_signing_secret_ref,
    wh_signing_algorithm = EXCLUDED.wh_signing_algorithm,
    wh_credentials_created_at = EXCLUDED.wh_credentials_created_at,
    wh_credentials_regenerated_at = EXCLUDED.wh_credentials_regenerated_at,
    last_used_at = EXCLUDED.last_used_at,
    updated_at = EXCLUDED.updated_at
`

type ServiceAccountUpsertParams struct {
	ID                         string     `db:"id"`
	Code                       string     `db:"code"`
	Name                       string     `db:"name"`
	Description                *string    `db:"description"`
	ApplicationID              *string    `db:"application_id"`
	Scope                      *string    `db:"scope"`
	ClientIds                  []string   `db:"client_ids"`
	Active                     bool       `db:"active"`
	WhAuthType                 *string    `db:"wh_auth_type"`
	WhAuthTokenRef             *string    `db:"wh_auth_token_ref"`
	WhSigningSecretRef         *string    `db:"wh_signing_secret_ref"`
	WhSigningAlgorithm         *string    `db:"wh_signing_algorithm"`
	WhCredentialsCreatedAt     *time.Time `db:"wh_credentials_created_at"`
	WhCredentialsRegeneratedAt *time.Time `db:"wh_credentials_regenerated_at"`
	LastUsedAt                 *time.Time `db:"last_used_at"`
	CreatedAt                  time.Time  `db:"created_at"`
	UpdatedAt                  time.Time  `db:"updated_at"`
}

func (q *Queries) ServiceAccountUpsert(ctx context.Context, arg ServiceAccountUpsertParams) error {
	_, err := q.db.Exec(ctx, serviceAccountUpsert,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ApplicationID,
		arg.Scope,
		arg.ClientIds,
		arg.Active,
		arg.WhAuthType,
		arg.WhAuthTokenRef,
		arg.WhSigningSecretRef,
		arg.WhSigningAlgorithm,
		arg.WhCredentialsCreatedAt,
		arg.WhCredentialsRegeneratedAt,
		arg.LastUsedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
