// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package dbq

import (
	"context"
	"time"
)

const subscriptionConfigInsert = `-- name: SubscriptionConfigInsert :exec
INSERT INTO msg_subscription_custom_configs
    (subscription_id, config_key, config_value)
VALUES ($1, $2, $3)
`

type SubscriptionConfigInsertParams struct {
	SubscriptionID string `db:"subscription_id"`
	ConfigKey      string `db:"config_key"`
	ConfigValue    string `db:"config_value"`
}

func (q *Queries) SubscriptionConfigInsert(ctx context.Context, arg SubscriptionConfigInsertParams) error {
	_, err := q.db.Exec(ctx, subscriptionConfigInsert, arg.SubscriptionID, arg.ConfigKey, arg.ConfigValue)
	return err
}

const subscriptionConfigsClear = `-- name: SubscriptionConfigsClear :exec
DELETE FROM msg_subscription_custom_configs WHERE subscription_id = $1
`

func (q *Queries) SubscriptionConfigsClear(ctx context.Context, subscriptionID string) error {
	_, err := q.db.Exec(ctx, subscriptionConfigsClear, subscriptionID)
	return err
}

const subscriptionConfigsForSubs = `-- name: SubscriptionConfigsForSubs :many
SELECT subscription_id, config_key, config_value
FROM msg_subscription_custom_configs
WHERE subscription_id = ANY($1::text[])
`

type SubscriptionConfigsForSubsRow struct {
	SubscriptionID string `db:"subscription_id"`
	ConfigKey      string `db:"config_key"`
	ConfigValue    string `db:"config_value"`
}

func (q *Queries) SubscriptionConfigsForSubs(ctx context.Context, subscriptionIds []string) ([]SubscriptionConfigsForSubsRow, error) {
	rows, err := q.db.Query(ctx, subscriptionConfigsForSubs, subscriptionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionConfigsForSubsRow{}
	for rows.Next() {
		var i SubscriptionConfigsForSubsRow
		if err := rows.Scan(&i.SubscriptionID, &i.ConfigKey, &i.ConfigValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionDelete = `-- name: SubscriptionDelete :exec
DELETE FROM msg_subscriptions WHERE id = $1
`

func (q *Queries) SubscriptionDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, subscriptionDelete, id)
	return err
}

const subscriptionEventTypeInsert = `-- name: SubscriptionEventTypeInsert :exec
INSERT INTO msg_subscription_event_types
    (subscription_id, event_type_id, event_type_code, spec_version)
VALUES ($1, $2, $3, $4)
`

type SubscriptionEventTypeInsertParams struct {
	SubscriptionID string  `db:"subscription_id"`
	EventTypeID    *string `db:"event_type_id"`
	EventTypeCode  string  `db:"event_type_code"`
	SpecVersion    *string `db:"spec_version"`
}

func (q *Queries) SubscriptionEventTypeInsert(ctx context.Context, arg SubscriptionEventTypeInsertParams) error {
	_, err := q.db.Exec(ctx, subscriptionEventTypeInsert,
		arg.SubscriptionID,
		arg.EventTypeID,
		arg.EventTypeCode,
		arg.SpecVersion,
	)
	return err
}

const subscriptionEventTypesClear = `-- name: SubscriptionEventTypesClear :exec
DELETE FROM msg_subscription_event_types WHERE subscription_id = $1
`

func (q *Queries) SubscriptionEventTypesClear(ctx context.Context, subscriptionID string) error {
	_, err := q.db.Exec(ctx, subscriptionEventTypesClear, subscriptionID)
	return err
}

const subscriptionEventTypesForSubs = `-- name: SubscriptionEventTypesForSubs :many
SELECT subscription_id, event_type_id, event_type_code, spec_version
FROM msg_subscription_event_types
WHERE subscription_id = ANY($1::text[])
`

type SubscriptionEventTypesForSubsRow struct {
	SubscriptionID string  `db:"subscription_id"`
	EventTypeID    *string `db:"event_type_id"`
	EventTypeCode  string  `db:"event_type_code"`
	SpecVersion    *string `db:"spec_version"`
}

func (q *Queries) SubscriptionEventTypesForSubs(ctx context.Context, subscriptionIds []string) ([]SubscriptionEventTypesForSubsRow, error) {
	rows, err := q.db.Query(ctx, subscriptionEventTypesForSubs, subscriptionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionEventTypesForSubsRow{}
	for rows.Next() {
		var i SubscriptionEventTypesForSubsRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.EventTypeID,
			&i.EventTypeCode,
			&i.SpecVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionFindAll = `-- name: SubscriptionFindAll :many
SELECT id, code, application_code, name, description, client_id,
       client_identifier, client_scoped, target, queue,
       source, status, max_age_seconds, dispatch_pool_id, dispatch_pool_code,
       delay_seconds, sequence, mode, timeout_seconds, max_retries,
       service_account_id, data_only, created_at, updated_at, connection_id, created_by
FROM msg_subscriptions
ORDER BY code
`

func (q *Queries) SubscriptionFindAll(ctx context.Context) ([]MsgSubscription, error) {
	rows, err := q.db.Query(ctx, subscriptionFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsgSubscription{}
	for rows.Next() {
		var i MsgSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ApplicationCode,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.ClientIdentifier,
			&i.ClientScoped,
			&i.Target,
			&i.Queue,
			&i.Source,
			&i.Status,
			&i.MaxAgeSeconds,
			&i.DispatchPoolID,
			&i.DispatchPoolCode,
			&i.DelaySeconds,
			&i.Sequence,
			&i.Mode,
			&i.TimeoutSeconds,
			&i.MaxRetries,
			&i.ServiceAccountID,
			&i.DataOnly,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionFindByCodeAnchor = `-- name: SubscriptionFindByCodeAnchor :one
SELECT id, code, application_code, name, description, client_id,
       client_identifier, client_scoped, target, queue,
       source, status, max_age_seconds, dispatch_pool_id, dispatch_pool_code,
       delay_seconds, sequence, mode, timeout_seconds, max_retries,
       service_account_id, data_only, created_at, updated_at, connection_id, created_by
FROM msg_subscriptions
WHERE code = $1 AND client_id IS NULL
`

func (q *Queries) SubscriptionFindByCodeAnchor(ctx context.Context, code string) (MsgSubscription, error) {
	row := q.db.QueryRow(ctx, subscriptionFindByCodeAnchor, code)
	var i MsgSubscription
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ApplicationCode,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.ClientScoped,
		&i.Target,
		&i.Queue,
		&i.Source,
		&i.Status,
		&i.MaxAgeSeconds,
		&i.DispatchPoolID,
		&i.DispatchPoolCode,
		&i.DelaySeconds,
		&i.Sequence,
		&i.Mode,
		&i.TimeoutSeconds,
		&i.MaxRetries,
		&i.ServiceAccountID,
		&i.DataOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionID,
		&i.CreatedBy,
	)
	return i, err
}

const subscriptionFindByCodeClient = `-- name: SubscriptionFindByCodeClient :one
SELECT id, code, application_code, name, description, client_id,
       client_identifier, client_scoped, target, queue,
       source, status, max_age_seconds, dispatch_pool_id, dispatch_pool_code,
       delay_seconds, sequence, mode, timeout_seconds, max_retries,
       service_account_id, data_only, created_at, updated_at, connection_id, created_by
FROM msg_subscriptions
WHERE code = $1 AND client_id = $2
`

type SubscriptionFindByCodeClientParams struct {
	Code     string  `db:"code"`
	ClientID *string `db:"client_id"`
}

func (q *Queries) SubscriptionFindByCodeClient(ctx context.Context, arg SubscriptionFindByCodeClientParams) (MsgSubscription, error) {
	row := q.db.QueryRow(ctx, subscriptionFindByCodeClient, arg.Code, arg.ClientID)
	var i MsgSubscription
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ApplicationCode,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.ClientScoped,
		&i.Target,
		&i.Queue,
		&i.Source,
		&i.Status,
		&i.MaxAgeSeconds,
		&i.DispatchPoolID,
		&i.DispatchPoolCode,
		&i.DelaySeconds,
		&i.Sequence,
		&i.Mode,
		&i.TimeoutSeconds,
		&i.MaxRetries,
		&i.ServiceAccountID,
		&i.DataOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionID,
		&i.CreatedBy,
	)
	return i, err
}

const subscriptionFindByID = `-- name: SubscriptionFindByID :one

SELECT id, code, application_code, name, description, client_id,
       client_identifier, client_scoped, target, queue,
       source, status, max_age_seconds, dispatch_pool_id, dispatch_pool_code,
       delay_seconds, sequence, mode, timeout_seconds, max_retries,
       service_account_id, data_only, created_at, updated_at, connection_id, created_by
FROM msg_subscriptions
WHERE id = $1
`

// Queries for msg_subscriptions + msg_subscription_event_types +
// msg_subscription_custom_configs.
//
// Schema columns differ from the previous Go port in several places:
//   - target (not endpoint)
//   - msg_subscription_event_types has no filter column
//   - msg_subscription_custom_configs uses config_key/config_value (not key/value)
//
// All of these were silent runtime bugs in the pre-sqlc repo.
// created_by was added Go-side in migration 035 (Rust never had it; its
// rows read back NULL).
func (q *Queries) SubscriptionFindByID(ctx context.Context, id string) (MsgSubscription, error) {
	row := q.db.QueryRow(ctx, subscriptionFindByID, id)
	var i MsgSubscription
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ApplicationCode,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.ClientIdentifier,
		&i.ClientScoped,
		&i.Target,
		&i.Queue,
		&i.Source,
		&i.Status,
		&i.MaxAgeSeconds,
		&i.DispatchPoolID,
		&i.DispatchPoolCode,
		&i.DelaySeconds,
		&i.Sequence,
		&i.Mode,
		&i.TimeoutSeconds,
		&i.MaxRetries,
		&i.ServiceAccountID,
		&i.DataOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionID,
		&i.CreatedBy,
	)
	return i, err
}

const subscriptionUpsert = `-- name: SubscriptionUpsert :exec
INSERT INTO msg_subscriptions
    (id, code, application_code, name, description, client_id, client_identifier,
     client_scoped, connection_id, target, queue, source, status, max_age_seconds,
     dispatch_pool_id, dispatch_pool_code, delay_seconds, sequence, mode,
     timeout_seconds, max_retries, service_account_id, data_only,
     created_by, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    target = EXCLUDED.target,
    status = EXCLUDED.status,
    max_age_seconds = EXCLUDED.max_age_seconds,
    dispatch_pool_id = EXCLUDED.dispatch_pool_id,
    dispatch_pool_code = EXCLUDED.dispatch_pool_code,
    delay_seconds = EXCLUDED.delay_seconds,
    sequence = EXCLUDED.sequence,
    mode = EXCLUDED.mode,
    timeout_seconds = EXCLUDED.timeout_seconds,
    max_retries = EXCLUDED.max_retries,
    service_account_id = EXCLUDED.service_account_id,
    data_only = EXCLUDED.data_only,
    updated_at = EXCLUDED.updated_at
`

type SubscriptionUpsertParams struct {
	ID               string    `db:"id"`
	Code             string    `db:"code"`
	ApplicationCode  *string   `db:"application_code"`
	Name             string    `db:"name"`
	Description      *string   `db:"description"`
	ClientID         *string   `db:"client_id"`
	ClientIdentifier *string   `db:"client_identifier"`
	ClientScoped     bool      `db:"client_scoped"`
	ConnectionID     *string   `db:"connection_id"`
	Target           string    `db:"target"`
	Queue            *string   `db:"queue"`
	Source           string    `db:"source"`
	Status           string    `db:"status"`
	MaxAgeSeconds    int32     `db:"max_age_seconds"`
	DispatchPoolID   *string   `db:"dispatch_pool_id"`
	DispatchPoolCode *string   `db:"dispatch_pool_code"`
	DelaySeconds     int32     `db:"delay_seconds"`
	Sequence         int32     `db:"sequence"`
	Mode             string    `db:"mode"`
	TimeoutSeconds   int32     `db:"timeout_seconds"`
	MaxRetries       int32     `db:"max_retries"`
	ServiceAccountID *string   `db:"service_account_id"`
	DataOnly         bool      `db:"data_only"`
	CreatedBy        *string   `db:"created_by"`
	CreatedAt        time.Time `db:"created_at"`
	UpdatedAt        time.Time `db:"updated_at"`
}

func (q *Queries) SubscriptionUpsert(ctx context.Context, arg SubscriptionUpsertParams) error {
	_, err := q.db.Exec(ctx, subscriptionUpsert,
		arg.ID,
		arg.Code,
		arg.ApplicationCode,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.ClientIdentifier,
		arg.ClientScoped,
		arg.ConnectionID,
		arg.Target,
		arg.Queue,
		arg.Source,
		arg.Status,
		arg.MaxAgeSeconds,
		arg.DispatchPoolID,
		arg.DispatchPoolCode,
		arg.DelaySeconds,
		arg.Sequence,
		arg.Mode,
		arg.TimeoutSeconds,
		arg.MaxRetries,
		arg.ServiceAccountID,
		arg.DataOnly,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
